// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: sandbox/v1/sandbox.proto

package sandboxv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecFrame_Stream int32

const (
	ExecFrame_STREAM_UNSPECIFIED ExecFrame_Stream = 0
	ExecFrame_STDOUT             ExecFrame_Stream = 1
	ExecFrame_STDERR             ExecFrame_Stream = 2
)

// Enum value maps for ExecFrame_Stream.
var (
	ExecFrame_Stream_name = map[int32]string{
		0: "STREAM_UNSPECIFIED",
		1: "STDOUT",
		2: "STDERR",
	}
	ExecFrame_Stream_value = map[string]int32{
		"STREAM_UNSPECIFIED": 0,
		"STDOUT":             1,
		"STDERR":             2,
	}
)

func (x ExecFrame_Stream) Enum() *ExecFrame_Stream {
	p := new(ExecFrame_Stream)
	*p = x
	return p
}

func (x ExecFrame_Stream) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ExecFrame_Stream) Descriptor() protoreflect.EnumDescriptor {
	return file_sandbox_v1_sandbox_proto_enumTypes[0].Descriptor()
}

func (ExecFrame_Stream) Type() protoreflect.EnumType {
	return &file_sandbox_v1_sandbox_proto_enumTypes[0]
}

func (x ExecFrame_Stream) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ExecFrame_Stream.Descriptor instead.
func (ExecFrame_Stream) EnumDescriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{8, 0}
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	ConfigDigest  string                 `protobuf:"bytes,2,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *HealthRequest) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *HealthRequest) GetConfigDigest() string {
	if x != nil {
		return x.ConfigDigest
	}
	return ""
}

type HealthResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	ProtocolMajor          uint32                 `protobuf:"varint,1,opt,name=protocol_major,json=protocolMajor,proto3" json:"protocol_major,omitempty"`
	DaemonVersion          string                 `protobuf:"bytes,2,opt,name=daemon_version,json=daemonVersion,proto3" json:"daemon_version,omitempty"`
	DockerAvailable        bool                   `protobuf:"varint,3,opt,name=docker_available,json=dockerAvailable,proto3" json:"docker_available,omitempty"`
	RunscAvailable         bool                   `protobuf:"varint,4,opt,name=runsc_available,json=runscAvailable,proto3" json:"runsc_available,omitempty"`
	NftablesAvailable      bool                   `protobuf:"varint,5,opt,name=nftables_available,json=nftablesAvailable,proto3" json:"nftables_available,omitempty"`
	CgroupV2Available      bool                   `protobuf:"varint,6,opt,name=cgroup_v2_available,json=cgroupV2Available,proto3" json:"cgroup_v2_available,omitempty"`
	ConfigDigest           string                 `protobuf:"bytes,7,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	DockerApiVersion       string                 `protobuf:"bytes,8,opt,name=docker_api_version,json=dockerApiVersion,proto3" json:"docker_api_version,omitempty"`
	RunscRuntimeRegistered bool                   `protobuf:"varint,9,opt,name=runsc_runtime_registered,json=runscRuntimeRegistered,proto3" json:"runsc_runtime_registered,omitempty"`
	ClientUidPolicyActive  bool                   `protobuf:"varint,10,opt,name=client_uid_policy_active,json=clientUidPolicyActive,proto3" json:"client_uid_policy_active,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetProtocolMajor() uint32 {
	if x != nil {
		return x.ProtocolMajor
	}
	return 0
}

func (x *HealthResponse) GetDaemonVersion() string {
	if x != nil {
		return x.DaemonVersion
	}
	return ""
}

func (x *HealthResponse) GetDockerAvailable() bool {
	if x != nil {
		return x.DockerAvailable
	}
	return false
}

func (x *HealthResponse) GetRunscAvailable() bool {
	if x != nil {
		return x.RunscAvailable
	}
	return false
}

func (x *HealthResponse) GetNftablesAvailable() bool {
	if x != nil {
		return x.NftablesAvailable
	}
	return false
}

func (x *HealthResponse) GetCgroupV2Available() bool {
	if x != nil {
		return x.CgroupV2Available
	}
	return false
}

func (x *HealthResponse) GetConfigDigest() string {
	if x != nil {
		return x.ConfigDigest
	}
	return ""
}

func (x *HealthResponse) GetDockerApiVersion() string {
	if x != nil {
		return x.DockerApiVersion
	}
	return ""
}

func (x *HealthResponse) GetRunscRuntimeRegistered() bool {
	if x != nil {
		return x.RunscRuntimeRegistered
	}
	return false
}

func (x *HealthResponse) GetClientUidPolicyActive() bool {
	if x != nil {
		return x.ClientUidPolicyActive
	}
	return false
}

type NetworkGrant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          string                 `protobuf:"bytes,1,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Ports         []uint32               `protobuf:"varint,2,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkGrant) Reset() {
	*x = NetworkGrant{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkGrant) ProtoMessage() {}

func (x *NetworkGrant) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkGrant.ProtoReflect.Descriptor instead.
func (*NetworkGrant) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkGrant) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *NetworkGrant) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

type AcquireRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SolverId       string                 `protobuf:"bytes,2,opt,name=solver_id,json=solverId,proto3" json:"solver_id,omitempty"`
	ProfileId      string                 `protobuf:"bytes,3,opt,name=profile_id,json=profileId,proto3" json:"profile_id,omitempty"`
	ConfigDigest   string                 `protobuf:"bytes,4,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,5,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AcquireRequest) Reset() {
	*x = AcquireRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireRequest) ProtoMessage() {}

func (x *AcquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireRequest.ProtoReflect.Descriptor instead.
func (*AcquireRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{4}
}

func (x *AcquireRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AcquireRequest) GetSolverId() string {
	if x != nil {
		return x.SolverId
	}
	return ""
}

func (x *AcquireRequest) GetProfileId() string {
	if x != nil {
		return x.ProfileId
	}
	return ""
}

func (x *AcquireRequest) GetConfigDigest() string {
	if x != nil {
		return x.ConfigDigest
	}
	return ""
}

func (x *AcquireRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *AcquireRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type AcquireResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	ConfigDigest  string                 `protobuf:"bytes,2,opt,name=config_digest,json=configDigest,proto3" json:"config_digest,omitempty"`
	FencingToken  uint64                 `protobuf:"varint,3,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	Reused        bool                   `protobuf:"varint,4,opt,name=reused,proto3" json:"reused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireResponse) Reset() {
	*x = AcquireResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireResponse) ProtoMessage() {}

func (x *AcquireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireResponse.ProtoReflect.Descriptor instead.
func (*AcquireResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{5}
}

func (x *AcquireResponse) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *AcquireResponse) GetConfigDigest() string {
	if x != nil {
		return x.ConfigDigest
	}
	return ""
}

func (x *AcquireResponse) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *AcquireResponse) GetReused() bool {
	if x != nil {
		return x.Reused
	}
	return false
}

type ProcessSpec struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Argv             []string               `protobuf:"bytes,1,rep,name=argv,proto3" json:"argv,omitempty"`
	Environment      map[string]string      `protobuf:"bytes,2,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	LogicalWorkspace string                 `protobuf:"bytes,3,opt,name=logical_workspace,json=logicalWorkspace,proto3" json:"logical_workspace,omitempty"`
	TimeoutSeconds   uint32                 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	NetworkGrants    []*NetworkGrant        `protobuf:"bytes,5,rep,name=network_grants,json=networkGrants,proto3" json:"network_grants,omitempty"`
	ToolId           string                 `protobuf:"bytes,6,opt,name=tool_id,json=toolId,proto3" json:"tool_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ProcessSpec) Reset() {
	*x = ProcessSpec{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessSpec) ProtoMessage() {}

func (x *ProcessSpec) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessSpec.ProtoReflect.Descriptor instead.
func (*ProcessSpec) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessSpec) GetArgv() []string {
	if x != nil {
		return x.Argv
	}
	return nil
}

func (x *ProcessSpec) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *ProcessSpec) GetLogicalWorkspace() string {
	if x != nil {
		return x.LogicalWorkspace
	}
	return ""
}

func (x *ProcessSpec) GetTimeoutSeconds() uint32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *ProcessSpec) GetNetworkGrants() []*NetworkGrant {
	if x != nil {
		return x.NetworkGrants
	}
	return nil
}

func (x *ProcessSpec) GetToolId() string {
	if x != nil {
		return x.ToolId
	}
	return ""
}

type ExecRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,2,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	Process        *ProcessSpec           `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	SolverId       string                 `protobuf:"bytes,5,opt,name=solver_id,json=solverId,proto3" json:"solver_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecRequest) Reset() {
	*x = ExecRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecRequest) ProtoMessage() {}

func (x *ExecRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecRequest.ProtoReflect.Descriptor instead.
func (*ExecRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{7}
}

func (x *ExecRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ExecRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *ExecRequest) GetProcess() *ProcessSpec {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *ExecRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ExecRequest) GetSolverId() string {
	if x != nil {
		return x.SolverId
	}
	return ""
}

type ExecFrame struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Sequence        uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	Stream          ExecFrame_Stream       `protobuf:"varint,3,opt,name=stream,proto3,enum=tga.sandbox.v1.ExecFrame_Stream" json:"stream,omitempty"`
	Data            []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ExecFrame) Reset() {
	*x = ExecFrame{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecFrame) ProtoMessage() {}

func (x *ExecFrame) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecFrame.ProtoReflect.Descriptor instead.
func (*ExecFrame) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{8}
}

func (x *ExecFrame) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *ExecFrame) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *ExecFrame) GetStream() ExecFrame_Stream {
	if x != nil {
		return x.Stream
	}
	return ExecFrame_STREAM_UNSPECIFIED
}

func (x *ExecFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ExecResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      *int32                 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	Signal        string                 `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	TimedOut      bool                   `protobuf:"varint,3,opt,name=timed_out,json=timedOut,proto3" json:"timed_out,omitempty"`
	Truncated     bool                   `protobuf:"varint,4,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecResult) Reset() {
	*x = ExecResult{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecResult) ProtoMessage() {}

func (x *ExecResult) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecResult.ProtoReflect.Descriptor instead.
func (*ExecResult) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{9}
}

func (x *ExecResult) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

func (x *ExecResult) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *ExecResult) GetTimedOut() bool {
	if x != nil {
		return x.TimedOut
	}
	return false
}

func (x *ExecResult) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

type ExecEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ExecEvent_Frame
	//	*ExecEvent_Result
	Event         isExecEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecEvent) Reset() {
	*x = ExecEvent{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecEvent) ProtoMessage() {}

func (x *ExecEvent) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecEvent.ProtoReflect.Descriptor instead.
func (*ExecEvent) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{10}
}

func (x *ExecEvent) GetEvent() isExecEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ExecEvent) GetFrame() *ExecFrame {
	if x != nil {
		if x, ok := x.Event.(*ExecEvent_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

func (x *ExecEvent) GetResult() *ExecResult {
	if x != nil {
		if x, ok := x.Event.(*ExecEvent_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isExecEvent_Event interface {
	isExecEvent_Event()
}

type ExecEvent_Frame struct {
	Frame *ExecFrame `protobuf:"bytes,1,opt,name=frame,proto3,oneof"`
}

type ExecEvent_Result struct {
	Result *ExecResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*ExecEvent_Frame) isExecEvent_Event() {}

func (*ExecEvent_Result) isExecEvent_Event() {}

type ProcessStart struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	InstanceId     string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	FencingToken   uint64                 `protobuf:"varint,2,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	Process        *ProcessSpec           `protobuf:"bytes,3,opt,name=process,proto3" json:"process,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	SolverId       string                 `protobuf:"bytes,5,opt,name=solver_id,json=solverId,proto3" json:"solver_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ProcessStart) Reset() {
	*x = ProcessStart{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessStart) ProtoMessage() {}

func (x *ProcessStart) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessStart.ProtoReflect.Descriptor instead.
func (*ProcessStart) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessStart) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ProcessStart) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

func (x *ProcessStart) GetProcess() *ProcessSpec {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *ProcessStart) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ProcessStart) GetSolverId() string {
	if x != nil {
		return x.SolverId
	}
	return ""
}

type ProcessInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	CloseStdin    bool                   `protobuf:"varint,2,opt,name=close_stdin,json=closeStdin,proto3" json:"close_stdin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessInput) Reset() {
	*x = ProcessInput{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessInput) ProtoMessage() {}

func (x *ProcessInput) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessInput.ProtoReflect.Descriptor instead.
func (*ProcessInput) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{12}
}

func (x *ProcessInput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ProcessInput) GetCloseStdin() bool {
	if x != nil {
		return x.CloseStdin
	}
	return false
}

type ProcessOpened struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessOpened) Reset() {
	*x = ProcessOpened{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessOpened) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessOpened) ProtoMessage() {}

func (x *ProcessOpened) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessOpened.ProtoReflect.Descriptor instead.
func (*ProcessOpened) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{13}
}

func (x *ProcessOpened) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

type ProcessMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ProcessMessage_Start
	//	*ProcessMessage_Input
	//	*ProcessMessage_Opened
	//	*ProcessMessage_Frame
	//	*ProcessMessage_Result
	Message       isProcessMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessMessage) Reset() {
	*x = ProcessMessage{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessMessage) ProtoMessage() {}

func (x *ProcessMessage) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessMessage.ProtoReflect.Descriptor instead.
func (*ProcessMessage) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{14}
}

func (x *ProcessMessage) GetMessage() isProcessMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ProcessMessage) GetStart() *ProcessStart {
	if x != nil {
		if x, ok := x.Message.(*ProcessMessage_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ProcessMessage) GetInput() *ProcessInput {
	if x != nil {
		if x, ok := x.Message.(*ProcessMessage_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *ProcessMessage) GetOpened() *ProcessOpened {
	if x != nil {
		if x, ok := x.Message.(*ProcessMessage_Opened); ok {
			return x.Opened
		}
	}
	return nil
}

func (x *ProcessMessage) GetFrame() *ExecFrame {
	if x != nil {
		if x, ok := x.Message.(*ProcessMessage_Frame); ok {
			return x.Frame
		}
	}
	return nil
}

func (x *ProcessMessage) GetResult() *ExecResult {
	if x != nil {
		if x, ok := x.Message.(*ProcessMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isProcessMessage_Message interface {
	isProcessMessage_Message()
}

type ProcessMessage_Start struct {
	Start *ProcessStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ProcessMessage_Input struct {
	Input *ProcessInput `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type ProcessMessage_Opened struct {
	Opened *ProcessOpened `protobuf:"bytes,3,opt,name=opened,proto3,oneof"`
}

type ProcessMessage_Frame struct {
	Frame *ExecFrame `protobuf:"bytes,4,opt,name=frame,proto3,oneof"`
}

type ProcessMessage_Result struct {
	Result *ExecResult `protobuf:"bytes,5,opt,name=result,proto3,oneof"`
}

func (*ProcessMessage_Start) isProcessMessage_Message() {}

func (*ProcessMessage_Input) isProcessMessage_Message() {}

func (*ProcessMessage_Opened) isProcessMessage_Message() {}

func (*ProcessMessage_Frame) isProcessMessage_Message() {}

func (*ProcessMessage_Result) isProcessMessage_Message() {}

type StopProcessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProcessId     string                 `protobuf:"bytes,1,opt,name=process_id,json=processId,proto3" json:"process_id,omitempty"`
	FencingToken  uint64                 `protobuf:"varint,2,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopProcessRequest) Reset() {
	*x = StopProcessRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopProcessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopProcessRequest) ProtoMessage() {}

func (x *StopProcessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopProcessRequest.ProtoReflect.Descriptor instead.
func (*StopProcessRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{15}
}

func (x *StopProcessRequest) GetProcessId() string {
	if x != nil {
		return x.ProcessId
	}
	return ""
}

func (x *StopProcessRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

type InspectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	FencingToken  uint64                 `protobuf:"varint,2,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectRequest) Reset() {
	*x = InspectRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectRequest) ProtoMessage() {}

func (x *InspectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectRequest.ProtoReflect.Descriptor instead.
func (*InspectRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{16}
}

func (x *InspectRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InspectRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

type InspectResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	State           string                 `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Runtime         string                 `protobuf:"bytes,2,opt,name=runtime,proto3" json:"runtime,omitempty"`
	ActiveProcesses uint32                 `protobuf:"varint,3,opt,name=active_processes,json=activeProcesses,proto3" json:"active_processes,omitempty"`
	CreatedAt       string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InspectResponse) Reset() {
	*x = InspectResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectResponse) ProtoMessage() {}

func (x *InspectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectResponse.ProtoReflect.Descriptor instead.
func (*InspectResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{17}
}

func (x *InspectResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *InspectResponse) GetRuntime() string {
	if x != nil {
		return x.Runtime
	}
	return ""
}

func (x *InspectResponse) GetActiveProcesses() uint32 {
	if x != nil {
		return x.ActiveProcesses
	}
	return 0
}

func (x *InspectResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	FencingToken  uint64                 `protobuf:"varint,2,opt,name=fencing_token,json=fencingToken,proto3" json:"fencing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyRequest) Reset() {
	*x = DestroyRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyRequest) ProtoMessage() {}

func (x *DestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyRequest.ProtoReflect.Descriptor instead.
func (*DestroyRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{18}
}

func (x *DestroyRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DestroyRequest) GetFencingToken() uint64 {
	if x != nil {
		return x.FencingToken
	}
	return 0
}

type ReconcileRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ValidInstanceIds  []string               `protobuf:"bytes,1,rep,name=valid_instance_ids,json=validInstanceIds,proto3" json:"valid_instance_ids,omitempty"`
	GraceBeforeUnixMs int64                  `protobuf:"varint,2,opt,name=grace_before_unix_ms,json=graceBeforeUnixMs,proto3" json:"grace_before_unix_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReconcileRequest) Reset() {
	*x = ReconcileRequest{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileRequest) ProtoMessage() {}

func (x *ReconcileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileRequest.ProtoReflect.Descriptor instead.
func (*ReconcileRequest) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{19}
}

func (x *ReconcileRequest) GetValidInstanceIds() []string {
	if x != nil {
		return x.ValidInstanceIds
	}
	return nil
}

func (x *ReconcileRequest) GetGraceBeforeUnixMs() int64 {
	if x != nil {
		return x.GraceBeforeUnixMs
	}
	return 0
}

type ReconcileResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	DestroyedInstanceIds []string               `protobuf:"bytes,1,rep,name=destroyed_instance_ids,json=destroyedInstanceIds,proto3" json:"destroyed_instance_ids,omitempty"`
	Errors               []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ReconcileResponse) Reset() {
	*x = ReconcileResponse{}
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconcileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconcileResponse) ProtoMessage() {}

func (x *ReconcileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sandbox_v1_sandbox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconcileResponse.ProtoReflect.Descriptor instead.
func (*ReconcileResponse) Descriptor() ([]byte, []int) {
	return file_sandbox_v1_sandbox_proto_rawDescGZIP(), []int{20}
}

func (x *ReconcileResponse) GetDestroyedInstanceIds() []string {
	if x != nil {
		return x.DestroyedInstanceIds
	}
	return nil
}

func (x *ReconcileResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_sandbox_v1_sandbox_proto protoreflect.FileDescriptor

const file_sandbox_v1_sandbox_proto_rawDesc = "" +
	"\n" +
	"\x18sandbox/v1/sandbox.proto\x12\x0etga.sandbox.v1\"\a\n" +
	"\x05Empty\"[\n" +
	"\rHealthRequest\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x12#\n" +
	"\rconfig_digest\x18\x02 \x01(\tR\fconfigDigest\"\xd7\x03\n" +
	"\x0eHealthResponse\x12%\n" +
	"\x0eprotocol_major\x18\x01 \x01(\rR\rprotocolMajor\x12%\n" +
	"\x0edaemon_version\x18\x02 \x01(\tR\rdaemonVersion\x12)\n" +
	"\x10docker_available\x18\x03 \x01(\bR\x0fdockerAvailable\x12'\n" +
	"\x0frunsc_available\x18\x04 \x01(\bR\x0erunscAvailable\x12-\n" +
	"\x12nftables_available\x18\x05 \x01(\bR\x11nftablesAvailable\x12.\n" +
	"\x13cgroup_v2_available\x18\x06 \x01(\bR\x11cgroupV2Available\x12#\n" +
	"\rconfig_digest\x18\a \x01(\tR\fconfigDigest\x12,\n" +
	"\x12docker_api_version\x18\b \x01(\tR\x10dockerApiVersion\x128\n" +
	"\x18runsc_runtime_registered\x18\t \x01(\bR\x16runscRuntimeRegistered\x127\n" +
	"\x18client_uid_policy_active\x18\n" +
	" \x01(\bR\x15clientUidPolicyActive\"8\n" +
	"\fNetworkGrant\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12\x14\n" +
	"\x05ports\x18\x02 \x03(\rR\x05ports\"\xd8\x01\n" +
	"\x0eAcquireRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\tsolver_id\x18\x02 \x01(\tR\bsolverId\x12\x1d\n" +
	"\n" +
	"profile_id\x18\x03 \x01(\tR\tprofileId\x12#\n" +
	"\rconfig_digest\x18\x04 \x01(\tR\fconfigDigest\x12#\n" +
	"\rfencing_token\x18\x05 \x01(\x04R\ffencingToken\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"\x94\x01\n" +
	"\x0fAcquireResponse\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rconfig_digest\x18\x02 \x01(\tR\fconfigDigest\x12#\n" +
	"\rfencing_token\x18\x03 \x01(\x04R\ffencingToken\x12\x16\n" +
	"\x06reused\x18\x04 \x01(\bR\x06reused\"\xe5\x02\n" +
	"\vProcessSpec\x12\x12\n" +
	"\x04argv\x18\x01 \x03(\tR\x04argv\x12N\n" +
	"\venvironment\x18\x02 \x03(\v2,.tga.sandbox.v1.ProcessSpec.EnvironmentEntryR\venvironment\x12+\n" +
	"\x11logical_workspace\x18\x03 \x01(\tR\x10logicalWorkspace\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\rR\x0etimeoutSeconds\x12C\n" +
	"\x0enetwork_grants\x18\x05 \x03(\v2\x1c.tga.sandbox.v1.NetworkGrantR\rnetworkGrants\x12\x17\n" +
	"\atool_id\x18\x06 \x01(\tR\x06toolId\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\vExecRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rfencing_token\x18\x02 \x01(\x04R\ffencingToken\x125\n" +
	"\aprocess\x18\x03 \x01(\v2\x1b.tga.sandbox.v1.ProcessSpecR\aprocess\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tsolver_id\x18\x05 \x01(\tR\bsolverId\"\xdb\x01\n" +
	"\tExecFrame\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\x128\n" +
	"\x06stream\x18\x03 \x01(\x0e2 .tga.sandbox.v1.ExecFrame.StreamR\x06stream\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"8\n" +
	"\x06Stream\x12\x16\n" +
	"\x12STREAM_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06STDOUT\x10\x01\x12\n" +
	"\n" +
	"\x06STDERR\x10\x02\"\x8f\x01\n" +
	"\n" +
	"ExecResult\x12 \n" +
	"\texit_code\x18\x01 \x01(\x05H\x00R\bexitCode\x88\x01\x01\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\x12\x1b\n" +
	"\ttimed_out\x18\x03 \x01(\bR\btimedOut\x12\x1c\n" +
	"\ttruncated\x18\x04 \x01(\bR\ttruncatedB\f\n" +
	"\n" +
	"_exit_code\"}\n" +
	"\tExecEvent\x121\n" +
	"\x05frame\x18\x01 \x01(\v2\x19.tga.sandbox.v1.ExecFrameH\x00R\x05frame\x124\n" +
	"\x06result\x18\x02 \x01(\v2\x1a.tga.sandbox.v1.ExecResultH\x00R\x06resultB\a\n" +
	"\x05event\"\xd1\x01\n" +
	"\fProcessStart\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rfencing_token\x18\x02 \x01(\x04R\ffencingToken\x125\n" +
	"\aprocess\x18\x03 \x01(\v2\x1b.tga.sandbox.v1.ProcessSpecR\aprocess\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tsolver_id\x18\x05 \x01(\tR\bsolverId\"C\n" +
	"\fProcessInput\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1f\n" +
	"\vclose_stdin\x18\x02 \x01(\bR\n" +
	"closeStdin\".\n" +
	"\rProcessOpened\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\"\xa9\x02\n" +
	"\x0eProcessMessage\x124\n" +
	"\x05start\x18\x01 \x01(\v2\x1c.tga.sandbox.v1.ProcessStartH\x00R\x05start\x124\n" +
	"\x05input\x18\x02 \x01(\v2\x1c.tga.sandbox.v1.ProcessInputH\x00R\x05input\x127\n" +
	"\x06opened\x18\x03 \x01(\v2\x1d.tga.sandbox.v1.ProcessOpenedH\x00R\x06opened\x121\n" +
	"\x05frame\x18\x04 \x01(\v2\x19.tga.sandbox.v1.ExecFrameH\x00R\x05frame\x124\n" +
	"\x06result\x18\x05 \x01(\v2\x1a.tga.sandbox.v1.ExecResultH\x00R\x06resultB\t\n" +
	"\amessage\"X\n" +
	"\x12StopProcessRequest\x12\x1d\n" +
	"\n" +
	"process_id\x18\x01 \x01(\tR\tprocessId\x12#\n" +
	"\rfencing_token\x18\x02 \x01(\x04R\ffencingToken\"V\n" +
	"\x0eInspectRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rfencing_token\x18\x02 \x01(\x04R\ffencingToken\"\x8b\x01\n" +
	"\x0fInspectResponse\x12\x14\n" +
	"\x05state\x18\x01 \x01(\tR\x05state\x12\x18\n" +
	"\aruntime\x18\x02 \x01(\tR\aruntime\x12)\n" +
	"\x10active_processes\x18\x03 \x01(\rR\x0factiveProcesses\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"V\n" +
	"\x0eDestroyRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12#\n" +
	"\rfencing_token\x18\x02 \x01(\x04R\ffencingToken\"q\n" +
	"\x10ReconcileRequest\x12,\n" +
	"\x12valid_instance_ids\x18\x01 \x03(\tR\x10validInstanceIds\x12/\n" +
	"\x14grace_before_unix_ms\x18\x02 \x01(\x03R\x11graceBeforeUnixMs\"a\n" +
	"\x11ReconcileResponse\x124\n" +
	"\x16destroyed_instance_ids\x18\x01 \x03(\tR\x14destroyedInstanceIds\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors2\xe4\x04\n" +
	"\x0eSandboxService\x12G\n" +
	"\x06Health\x12\x1d.tga.sandbox.v1.HealthRequest\x1a\x1e.tga.sandbox.v1.HealthResponse\x12J\n" +
	"\aAcquire\x12\x1e.tga.sandbox.v1.AcquireRequest\x1a\x1f.tga.sandbox.v1.AcquireResponse\x12@\n" +
	"\x04Exec\x12\x1b.tga.sandbox.v1.ExecRequest\x1a\x19.tga.sandbox.v1.ExecEvent0\x01\x12Q\n" +
	"\vOpenProcess\x12\x1e.tga.sandbox.v1.ProcessMessage\x1a\x1e.tga.sandbox.v1.ProcessMessage(\x010\x01\x12H\n" +
	"\vStopProcess\x12\".tga.sandbox.v1.StopProcessRequest\x1a\x15.tga.sandbox.v1.Empty\x12J\n" +
	"\aInspect\x12\x1e.tga.sandbox.v1.InspectRequest\x1a\x1f.tga.sandbox.v1.InspectResponse\x12@\n" +
	"\aDestroy\x12\x1e.tga.sandbox.v1.DestroyRequest\x1a\x15.tga.sandbox.v1.Empty\x12P\n" +
	"\tReconcile\x12 .tga.sandbox.v1.ReconcileRequest\x1a!.tga.sandbox.v1.ReconcileResponseB=Z;github.com/team-gipsy/tga-sandboxd/api/sandbox/v1;sandboxv1b\x06proto3"

var (
	file_sandbox_v1_sandbox_proto_rawDescOnce sync.Once
	file_sandbox_v1_sandbox_proto_rawDescData []byte
)

func file_sandbox_v1_sandbox_proto_rawDescGZIP() []byte {
	file_sandbox_v1_sandbox_proto_rawDescOnce.Do(func() {
		file_sandbox_v1_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sandbox_v1_sandbox_proto_rawDesc), len(file_sandbox_v1_sandbox_proto_rawDesc)))
	})
	return file_sandbox_v1_sandbox_proto_rawDescData
}

var file_sandbox_v1_sandbox_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_sandbox_v1_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_sandbox_v1_sandbox_proto_goTypes = []any{
	(ExecFrame_Stream)(0),      // 0: tga.sandbox.v1.ExecFrame.Stream
	(*Empty)(nil),              // 1: tga.sandbox.v1.Empty
	(*HealthRequest)(nil),      // 2: tga.sandbox.v1.HealthRequest
	(*HealthResponse)(nil),     // 3: tga.sandbox.v1.HealthResponse
	(*NetworkGrant)(nil),       // 4: tga.sandbox.v1.NetworkGrant
	(*AcquireRequest)(nil),     // 5: tga.sandbox.v1.AcquireRequest
	(*AcquireResponse)(nil),    // 6: tga.sandbox.v1.AcquireResponse
	(*ProcessSpec)(nil),        // 7: tga.sandbox.v1.ProcessSpec
	(*ExecRequest)(nil),        // 8: tga.sandbox.v1.ExecRequest
	(*ExecFrame)(nil),          // 9: tga.sandbox.v1.ExecFrame
	(*ExecResult)(nil),         // 10: tga.sandbox.v1.ExecResult
	(*ExecEvent)(nil),          // 11: tga.sandbox.v1.ExecEvent
	(*ProcessStart)(nil),       // 12: tga.sandbox.v1.ProcessStart
	(*ProcessInput)(nil),       // 13: tga.sandbox.v1.ProcessInput
	(*ProcessOpened)(nil),      // 14: tga.sandbox.v1.ProcessOpened
	(*ProcessMessage)(nil),     // 15: tga.sandbox.v1.ProcessMessage
	(*StopProcessRequest)(nil), // 16: tga.sandbox.v1.StopProcessRequest
	(*InspectRequest)(nil),     // 17: tga.sandbox.v1.InspectRequest
	(*InspectResponse)(nil),    // 18: tga.sandbox.v1.InspectResponse
	(*DestroyRequest)(nil),     // 19: tga.sandbox.v1.DestroyRequest
	(*ReconcileRequest)(nil),   // 20: tga.sandbox.v1.ReconcileRequest
	(*ReconcileResponse)(nil),  // 21: tga.sandbox.v1.ReconcileResponse
	nil,                        // 22: tga.sandbox.v1.ProcessSpec.EnvironmentEntry
}
var file_sandbox_v1_sandbox_proto_depIdxs = []int32{
	22, // 0: tga.sandbox.v1.ProcessSpec.environment:type_name -> tga.sandbox.v1.ProcessSpec.EnvironmentEntry
	4,  // 1: tga.sandbox.v1.ProcessSpec.network_grants:type_name -> tga.sandbox.v1.NetworkGrant
	7,  // 2: tga.sandbox.v1.ExecRequest.process:type_name -> tga.sandbox.v1.ProcessSpec
	0,  // 3: tga.sandbox.v1.ExecFrame.stream:type_name -> tga.sandbox.v1.ExecFrame.Stream
	9,  // 4: tga.sandbox.v1.ExecEvent.frame:type_name -> tga.sandbox.v1.ExecFrame
	10, // 5: tga.sandbox.v1.ExecEvent.result:type_name -> tga.sandbox.v1.ExecResult
	7,  // 6: tga.sandbox.v1.ProcessStart.process:type_name -> tga.sandbox.v1.ProcessSpec
	12, // 7: tga.sandbox.v1.ProcessMessage.start:type_name -> tga.sandbox.v1.ProcessStart
	13, // 8: tga.sandbox.v1.ProcessMessage.input:type_name -> tga.sandbox.v1.ProcessInput
	14, // 9: tga.sandbox.v1.ProcessMessage.opened:type_name -> tga.sandbox.v1.ProcessOpened
	9,  // 10: tga.sandbox.v1.ProcessMessage.frame:type_name -> tga.sandbox.v1.ExecFrame
	10, // 11: tga.sandbox.v1.ProcessMessage.result:type_name -> tga.sandbox.v1.ExecResult
	2,  // 12: tga.sandbox.v1.SandboxService.Health:input_type -> tga.sandbox.v1.HealthRequest
	5,  // 13: tga.sandbox.v1.SandboxService.Acquire:input_type -> tga.sandbox.v1.AcquireRequest
	8,  // 14: tga.sandbox.v1.SandboxService.Exec:input_type -> tga.sandbox.v1.ExecRequest
	15, // 15: tga.sandbox.v1.SandboxService.OpenProcess:input_type -> tga.sandbox.v1.ProcessMessage
	16, // 16: tga.sandbox.v1.SandboxService.StopProcess:input_type -> tga.sandbox.v1.StopProcessRequest
	17, // 17: tga.sandbox.v1.SandboxService.Inspect:input_type -> tga.sandbox.v1.InspectRequest
	19, // 18: tga.sandbox.v1.SandboxService.Destroy:input_type -> tga.sandbox.v1.DestroyRequest
	20, // 19: tga.sandbox.v1.SandboxService.Reconcile:input_type -> tga.sandbox.v1.ReconcileRequest
	3,  // 20: tga.sandbox.v1.SandboxService.Health:output_type -> tga.sandbox.v1.HealthResponse
	6,  // 21: tga.sandbox.v1.SandboxService.Acquire:output_type -> tga.sandbox.v1.AcquireResponse
	11, // 22: tga.sandbox.v1.SandboxService.Exec:output_type -> tga.sandbox.v1.ExecEvent
	15, // 23: tga.sandbox.v1.SandboxService.OpenProcess:output_type -> tga.sandbox.v1.ProcessMessage
	1,  // 24: tga.sandbox.v1.SandboxService.StopProcess:output_type -> tga.sandbox.v1.Empty
	18, // 25: tga.sandbox.v1.SandboxService.Inspect:output_type -> tga.sandbox.v1.InspectResponse
	1,  // 26: tga.sandbox.v1.SandboxService.Destroy:output_type -> tga.sandbox.v1.Empty
	21, // 27: tga.sandbox.v1.SandboxService.Reconcile:output_type -> tga.sandbox.v1.ReconcileResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_sandbox_v1_sandbox_proto_init() }
func file_sandbox_v1_sandbox_proto_init() {
	if File_sandbox_v1_sandbox_proto != nil {
		return
	}
	file_sandbox_v1_sandbox_proto_msgTypes[9].OneofWrappers = []any{}
	file_sandbox_v1_sandbox_proto_msgTypes[10].OneofWrappers = []any{
		(*ExecEvent_Frame)(nil),
		(*ExecEvent_Result)(nil),
	}
	file_sandbox_v1_sandbox_proto_msgTypes[14].OneofWrappers = []any{
		(*ProcessMessage_Start)(nil),
		(*ProcessMessage_Input)(nil),
		(*ProcessMessage_Opened)(nil),
		(*ProcessMessage_Frame)(nil),
		(*ProcessMessage_Result)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sandbox_v1_sandbox_proto_rawDesc), len(file_sandbox_v1_sandbox_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sandbox_v1_sandbox_proto_goTypes,
		DependencyIndexes: file_sandbox_v1_sandbox_proto_depIdxs,
		EnumInfos:         file_sandbox_v1_sandbox_proto_enumTypes,
		MessageInfos:      file_sandbox_v1_sandbox_proto_msgTypes,
	}.Build()
	File_sandbox_v1_sandbox_proto = out.File
	file_sandbox_v1_sandbox_proto_goTypes = nil
	file_sandbox_v1_sandbox_proto_depIdxs = nil
}
