# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from tga.sandbox.api.sandbox.v1 import sandbox_pb2 as sandbox_dot_v1_dot_sandbox__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sandbox/v1/sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/tga.sandbox.v1.SandboxService/Health',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.HealthRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Acquire = channel.unary_unary(
                '/tga.sandbox.v1.SandboxService/Acquire',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.AcquireRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.AcquireResponse.FromString,
                _registered_method=True)
        self.Exec = channel.unary_stream(
                '/tga.sandbox.v1.SandboxService/Exec',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ExecEvent.FromString,
                _registered_method=True)
        self.OpenProcess = channel.stream_stream(
                '/tga.sandbox.v1.SandboxService/OpenProcess',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.ProcessMessage.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ProcessMessage.FromString,
                _registered_method=True)
        self.StopProcess = channel.unary_unary(
                '/tga.sandbox.v1.SandboxService/StopProcess',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.StopProcessRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.Empty.FromString,
                _registered_method=True)
        self.Inspect = channel.unary_unary(
                '/tga.sandbox.v1.SandboxService/Inspect',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.InspectRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.InspectResponse.FromString,
                _registered_method=True)
        self.Destroy = channel.unary_unary(
                '/tga.sandbox.v1.SandboxService/Destroy',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.DestroyRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.Empty.FromString,
                _registered_method=True)
        self.Reconcile = channel.unary_unary(
                '/tga.sandbox.v1.SandboxService/Reconcile',
                request_serializer=sandbox_dot_v1_dot_sandbox__pb2.ReconcileRequest.SerializeToString,
                response_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ReconcileResponse.FromString,
                _registered_method=True)


class SandboxServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Acquire(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenProcess(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopProcess(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Inspect(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Destroy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Reconcile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.HealthRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.HealthResponse.SerializeToString,
            ),
            'Acquire': grpc.unary_unary_rpc_method_handler(
                    servicer.Acquire,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.AcquireRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.AcquireResponse.SerializeToString,
            ),
            'Exec': grpc.unary_stream_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.ExecEvent.SerializeToString,
            ),
            'OpenProcess': grpc.stream_stream_rpc_method_handler(
                    servicer.OpenProcess,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ProcessMessage.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.ProcessMessage.SerializeToString,
            ),
            'StopProcess': grpc.unary_unary_rpc_method_handler(
                    servicer.StopProcess,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.StopProcessRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.Empty.SerializeToString,
            ),
            'Inspect': grpc.unary_unary_rpc_method_handler(
                    servicer.Inspect,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.InspectRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.InspectResponse.SerializeToString,
            ),
            'Destroy': grpc.unary_unary_rpc_method_handler(
                    servicer.Destroy,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.DestroyRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.Empty.SerializeToString,
            ),
            'Reconcile': grpc.unary_unary_rpc_method_handler(
                    servicer.Reconcile,
                    request_deserializer=sandbox_dot_v1_dot_sandbox__pb2.ReconcileRequest.FromString,
                    response_serializer=sandbox_dot_v1_dot_sandbox__pb2.ReconcileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tga.sandbox.v1.SandboxService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tga.sandbox.v1.SandboxService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SandboxService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tga.sandbox.v1.SandboxService/Health',
            sandbox_dot_v1_dot_sandbox__pb2.HealthRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Acquire(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tga.sandbox.v1.SandboxService/Acquire',
            sandbox_dot_v1_dot_sandbox__pb2.AcquireRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.AcquireResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/tga.sandbox.v1.SandboxService/Exec',
            sandbox_dot_v1_dot_sandbox__pb2.ExecRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.ExecEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenProcess(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tga.sandbox.v1.SandboxService/OpenProcess',
            sandbox_dot_v1_dot_sandbox__pb2.ProcessMessage.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.ProcessMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopProcess(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tga.sandbox.v1.SandboxService/StopProcess',
            sandbox_dot_v1_dot_sandbox__pb2.StopProcessRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Inspect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tga.sandbox.v1.SandboxService/Inspect',
            sandbox_dot_v1_dot_sandbox__pb2.InspectRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.InspectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Destroy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tga.sandbox.v1.SandboxService/Destroy',
            sandbox_dot_v1_dot_sandbox__pb2.DestroyRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Reconcile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tga.sandbox.v1.SandboxService/Reconcile',
            sandbox_dot_v1_dot_sandbox__pb2.ReconcileRequest.SerializeToString,
            sandbox_dot_v1_dot_sandbox__pb2.ReconcileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
