"""Persistence ports expressed only in domain/application vocabulary.

These intentionally small protocols are migration seams.  Later phases may
add richer domain-specific operations without exposing ``sqlite3.Row`` or a
concrete database connection to callers.
"""

from __future__ import annotations

from typing import Any, Protocol

from tga.domain.evidence.artifacts import Artifact
from tga.domain.evidence.claims import EvidenceClaim
from tga.domain.evidence.findings import Finding
from tga.domain.events import AgentEvent
from tga.domain.knowledge.items import KnowledgeItem
from tga.domain.planning.global_plan import GlobalPlan
from tga.domain.planning.local_plan import LocalPlan
from tga.domain.solver.instances import SolverInstance
from tga.domain.solver.assignments import SolverAssignment
from tga.domain.solver.results import ReportResult, ReviewResult, WorkerResult
from tga.domain.solver.team_runtime import TeamRuntimeState
from tga.domain.solver.leases import SolverLease, TaskOrchestratorLease
from tga.domain.solver.runs import SolverRun
from tga.domain.runtime.models import SessionRecord
from tga.domain.task.models import TGATask
from tga.domain.task.spec import TaskSpec
from tga.domain.task.hints import TaskHint
from tga.domain.task.interventions import UserIntervention
from tga.domain.skills.models import (
    SkillActivation,
    SkillSelectionDecision,
    SolverSkillSnapshot,
    TaskCommonSkillSnapshot,
)


class TaskRepository(Protocol):
    def get_task(self, task_id: str) -> TGATask | None: ...
    def create_task(self, task: TGATask) -> None: ...
    def update_task(self, task: TGATask) -> None: ...
    def get_task_spec(self, task_id: str) -> TaskSpec | None: ...
    def save_task_spec(self, spec: TaskSpec) -> None: ...
    def save_hint(self, hint: TaskHint) -> None: ...
    def list_hints(self, task_id: str) -> list[TaskHint]: ...
    def add_intervention(self, intervention: UserIntervention) -> None: ...
    def list_interventions(self, task_id: str) -> list[UserIntervention]: ...
    def save_task_common_skill_snapshot(self, snapshot: TaskCommonSkillSnapshot) -> None: ...
    def get_task_common_skill_snapshot(self, task_id: str) -> TaskCommonSkillSnapshot | None: ...


class SessionRepository(Protocol):
    def get_session(self, task_id: str) -> SessionRecord | None: ...
    def create_session(self, session: SessionRecord) -> SessionRecord: ...


class SolverRepository(Protocol):
    def get_solver(self, solver_id: str) -> SolverInstance | None: ...
    def list_solvers(self, task_id: str) -> list[SolverInstance]: ...
    def lease_fencing_token(self, solver_id: str) -> int | None: ...
    def add_solver(self, solver: SolverInstance) -> None: ...
    def update_solver_status(self, solver_id: str, status: str) -> SolverInstance: ...
    def acquire_lease(self, task_id: str, solver_id: str, owner_id: str, *, ttl_seconds: float, now: Any | None = None) -> bool: ...
    def renew_lease(self, task_id: str, solver_id: str, owner_id: str, *, ttl_seconds: float, now: Any | None = None) -> bool: ...
    def release_lease(self, task_id: str, solver_id: str, owner_id: str) -> bool: ...
    def acquire_lease_handle(self, task_id: str, solver_id: str, owner_id: str, *, ttl_seconds: float, now: Any | None = None, max_active_workers: int | None = None) -> SolverLease | None: ...
    def renew_lease_handle(self, lease: SolverLease, *, ttl_seconds: float, now: Any | None = None) -> SolverLease | None: ...
    def validate_lease(self, lease: SolverLease, *, now: Any | None = None) -> bool: ...
    def release_lease_handle(self, lease: SolverLease) -> bool: ...
    def revoke_task_leases(self, task_id: str) -> int: ...
    def save_solver_skill_snapshot(self, snapshot: SolverSkillSnapshot) -> None: ...
    def get_solver_skill_snapshot(self, solver_id: str) -> SolverSkillSnapshot | None: ...
    def save_skill_selection_decision(self, decision: SkillSelectionDecision) -> None: ...
    def get_skill_selection_decision(self, decision_id: str) -> SkillSelectionDecision | None: ...
    def list_skill_selection_decisions(
        self, task_id: str, *, solver_id: str | None = None
    ) -> list[SkillSelectionDecision]: ...
    def save_skill_activation(self, activation: SkillActivation) -> None: ...
    def list_skill_activations(self, solver_id: str) -> list[SkillActivation]: ...
    def save_worker_result(self, result: WorkerResult, *, version: int = 1) -> str: ...
    def get_worker_result(self, result_id: str) -> WorkerResult | None: ...
    def list_worker_results(self, task_id: str) -> list[WorkerResult]: ...


class OrchestrationRepository(Protocol):
    def get_state(self, task_id: str) -> TeamRuntimeState | None: ...
    def save_state(self, state: TeamRuntimeState) -> TeamRuntimeState: ...
    def acquire_task_lease(self, task_id: str, owner_id: str, *, ttl_seconds: float, now: Any | None = None) -> TaskOrchestratorLease | None: ...
    def renew_task_lease(self, lease: TaskOrchestratorLease, *, ttl_seconds: float, now: Any | None = None) -> TaskOrchestratorLease | None: ...
    def validate_task_lease(self, lease: TaskOrchestratorLease, *, now: Any | None = None) -> bool: ...
    def release_task_lease(self, lease: TaskOrchestratorLease) -> bool: ...
    def get_assignment(self, assignment_id: str) -> SolverAssignment | None: ...
    def get_assignment_for_solver(self, solver_id: str) -> SolverAssignment | None: ...
    def list_assignments(self, task_id: str) -> list[SolverAssignment]: ...
    def save_assignment(self, assignment: SolverAssignment) -> SolverAssignment: ...
    def complete_assignment(self, assignment_id: str, *, finished_at: str) -> SolverAssignment: ...
    def cancel_assignment(self, assignment_id: str, *, finished_at: str) -> SolverAssignment: ...
    def create_solver_run(self, run: SolverRun) -> SolverRun: ...
    def get_solver_run(self, run_id: str) -> SolverRun | None: ...
    def list_solver_runs(self, task_id: str) -> list[SolverRun]: ...
    def active_run_fencing_token(self, solver_id: str) -> int | None: ...
    def claim_solver_run(self, run_id: str, owner_id: str, *, ttl_seconds: float, expected_version: int, max_active_workers: int | None = None, now: Any | None = None) -> SolverRun | None: ...
    def start_solver_run(self, run_id: str, owner_id: str, fencing_token: int, *, now: Any | None = None) -> SolverRun: ...
    def reserve_solver_run_turn(self, run_id: str, owner_id: str, fencing_token: int, *, now: Any | None = None) -> SolverRun | None: ...
    def renew_solver_run(self, run_id: str, owner_id: str, fencing_token: int, *, ttl_seconds: float, now: Any | None = None) -> SolverRun | None: ...
    def suspend_solver_run_for_approval(self, run_id: str, owner_id: str, fencing_token: int, *, now: Any | None = None) -> SolverRun: ...
    def resume_solver_run_after_approval(self, solver_id: str, intent_id: str | None, *, now: Any | None = None) -> SolverRun | None: ...
    def finish_solver_run(self, run_id: str, owner_id: str, fencing_token: int, *, state: str, result_id: str | None = None, error_code: str | None = None, error_message: str | None = None, now: Any | None = None) -> SolverRun: ...
    def expire_solver_runs(self, *, now: Any | None = None) -> list[SolverRun]: ...
    def cancel_task_solver_runs(self, task_id: str, *, now: Any | None = None) -> list[SolverRun]: ...
    def save_review_result(self, result: ReviewResult) -> str: ...
    def save_report_result(self, result: ReportResult) -> str: ...


class TranscriptRepository(Protocol):
    def list_messages(self, task_id: str, solver_id: str) -> list[dict[str, Any]]: ...
    def append_message(self, task_id: str, solver_id: str, message: dict[str, Any]) -> None: ...


class PlanRepository(Protocol):
    def get_global_plan(self, task_id: str) -> GlobalPlan | None: ...
    def save_global_plan(self, plan: GlobalPlan) -> None: ...
    def compare_and_swap_global_plan(self, plan: GlobalPlan, *, expected_version: int, preserve_intent_lifecycle: bool = True) -> None: ...
    def claim_pending_intent(self, intent_id: str, solver_id: str, expected_version: int) -> Any: ...
    def get_intent_version(self, intent_id: str) -> int: ...
    def get_local_plan(self, solver_id: str, intent_id: str) -> LocalPlan | None: ...
    def save_local_plan(self, plan: LocalPlan) -> None: ...
    def update_intent_status(self, intent_id: str, status: str, *, expected_status: str | None = None) -> Any: ...
    def reset_intent_for_retry(self, intent_id: str) -> Any: ...


class KnowledgeRepository(Protocol):
    def get_knowledge(self, knowledge_id: str) -> KnowledgeItem | None: ...
    def list_knowledge(self, task_id: str) -> list[KnowledgeItem]: ...
    def add_knowledge(self, item: KnowledgeItem) -> None: ...
    def list_conflicts(self, task_id: str, *, status: str | None = None) -> list[Any]: ...
    def add_conflict(self, conflict: Any) -> None: ...
    def list_promotions(self, task_id: str, *, status: str | None = None) -> list[Any]: ...
    def add_promotion(self, proposal: Any) -> None: ...


class EvidenceRepository(Protocol):
    def get_artifact(self, artifact_id: str) -> Artifact | None: ...
    def list_artifacts(self, task_id: str) -> list[Artifact]: ...
    def page_artifacts(
        self, task_id: str, *, offset: int, limit: int
    ) -> tuple[int, list[Artifact]]: ...
    def add_artifact(self, artifact: Artifact) -> None: ...
    def get_evidence_claim(self, claim_id: str) -> EvidenceClaim | None: ...
    def list_evidence_claims(self, task_id: str) -> list[EvidenceClaim]: ...
    def page_evidence_claims(
        self, task_id: str, *, offset: int, limit: int
    ) -> tuple[int, list[EvidenceClaim]]: ...
    def add_evidence_claim(self, claim: EvidenceClaim) -> None: ...
    def get_finding(self, finding_id: str) -> Finding | None: ...
    def list_findings(self, task_id: str) -> list[Finding]: ...
    def page_findings(
        self, task_id: str, *, offset: int, limit: int
    ) -> tuple[int, list[Finding]]: ...
    def save_finding(self, finding: Finding) -> None: ...


class EventRepository(Protocol):
    def append_agent_event(
        self,
        task_id: str,
        type: str,
        payload: dict[str, Any],
        *,
        solver_id: str | None = None,
        intent_id: str | None = None,
    ) -> AgentEvent: ...

    def list_agent_events(
        self,
        task_id: str,
        *,
        after_seq: int = 0,
        limit: int | None = 200,
    ) -> list[AgentEvent]: ...
