import type { TaskMode } from "../modes";
import type { ExecutionPolicy, ModeConfig, ResourceRef } from "../api/tasks";
export type { TaskMode } from "../modes";
export type SessionStatus = "created" | "running" | "paused" | "blocked" | "completed" | "failed" | "cancelled";
export type ActionStatus = "proposed" | "approved" | "running" | "succeeded" | "failed" | "blocked" | "cancelled";
export type HypothesisStatus = "pending" | "testing" | "verified" | "rejected" | "inconclusive" | "superseded";
export type MemoryKind = "fact" | "evidence" | "failure_boundary" | "hint" | "constraint" | "decision";

export type SessionFile = { id: string; original_name: string; stored_name: string; relative_path: string; mime_type: string; size: number; sha256: string; kind: "task" | "hint"; media_kind: "image" | "text" | "document" | "archive" | "binary" | "other" };
export type RuntimeTask = { id: string; name: string; mode: TaskMode; target: string; scope: string[]; goal?: string; schema_version?: number; targets?: ResourceRef[]; hints?: ResourceRef[]; session_input?: { task_files: SessionFile[]; hint: { text?: string | null; files: SessionFile[] } }; mcp_capabilities?: { catalog_version: string; server_ids: string[]; tools: Array<{ provider_name: string; server_id: string; method: string; description?: string }> }; mode_config?: ModeConfig; execution_policy?: ExecutionPolicy };
export type RuntimeSolver = { id: string; role: "main" | "recon" | "targeted" | "research"; status: string; model_name?: string; parent_solver_id?: string | null; started_at?: string | null; finished_at?: string | null };
export type ChallengeView = { status: "unknown" | "active" | "solved" | "blocked" | "expired"; completion_proof_artifact_id?: string | null; status_reason: string };
export type RuntimeSubagent = { request: { id: string; parent_solver_id: string; role: RuntimeSolver["role"]; objective: string; hypothesis_ids: string[]; max_actions: number }; solver_id: string; status: string; output: { status?: string; artifact_ids: string[]; coverage_gaps: string[]; next_recommendation: string } | null; created_at?: string; updated_at?: string };
export type Hypothesis = {
  id: string; statement: string; attack_class: string; entry_point: string; rationale: string; next_test: string;
  status: HypothesisStatus; confidence: number; attempt_count: number; evidence_artifact_ids: string[];
  last_result: string; owner_solver_id?: string | null; created_at?: string; updated_at?: string;
};
export type MemoryEntry = { id: string; kind: MemoryKind; content: string; artifact_ids: string[]; source: string; supersedes_id?: string | null; created_at?: string; updated_at?: string };
export type StrategyStep = { id: string; title: string; instructions: string; expected_request: string; success_marker: string; failure_conditions: string[]; next_step_id?: string | null; risk: "passive" | "active" | "destructive"; status: "pending" | "testing" | "verified" | "rejected" | "superseded"; action_ids: string[]; evidence_artifact_ids: string[]; last_result: string };
export type StrategyCard = { id: string; task_id: string; title: string; summary: string; claims: string[]; prerequisites: string[]; target_version_checks: string[]; status: StrategyStep["status"]; active_step_id?: string | null; sources: Array<{ hint_id?: string | null; url?: string | null; artifact_id?: string | null; extraction_status: "not_requested" | "blocked_out_of_scope" | "failed" | "extracted"; source_refs: string[] }>; steps: StrategyStep[]; created_at?: string; updated_at?: string };
export type RuntimeArtifact = { id: string; task_id?: string; kind: string; path: string; tool?: string | null; target?: string | null; input_id?: string | null; provenance?: Record<string, unknown>; created_at?: string; excerpt?: string; status?: number; method?: string; truncated?: boolean };
export type RuntimeAction = { id: string; solver_id?: string; capability: string; target: string; actual_target?: string | null; input_id?: string | null; target_ref?: string | null; authorization?: Record<string, unknown>; provenance?: Record<string, unknown>; status: ActionStatus; hypothesis_id?: string | null; strategy_card_id?: string | null; strategy_step_id?: string | null; rationale?: string; expected_outcome?: string; retry_reason?: string; alternative_analysis?: string; expected_side_effects?: string; summary?: string; artifact_ids: string[]; error?: { code?: string; message?: string } | null; created_at?: string; updated_at?: string; arguments?: Record<string, unknown> };
export type ConfirmedFlag = { value: string; evidence_artifact_id: string; created_at?: string };
export type RuntimeFinding = { id: string; title: string; target: string; severity: string; status: "candidate" | "confirmed" | "rejected"; evidence_artifact_id?: string | null; evidence_excerpt?: string | null; remediation?: string | null };
export type SkillRef = { name: string; version?: string; source?: string };
export type EventPayload = {
  action_id?: string; capability?: string; target?: string; hypothesis_id?: string; statement?: string; attack_class?: string;
  status?: string; summary?: string; rationale?: string; reason?: string; reminder?: string; value?: string; kind?: string;
  evidence_artifact_id?: string; artifact_id?: string; artifact_ids?: string[]; finding_id?: string; role?: string; model_name?: string;
  max_turns?: number; action?: string; error?: { code?: string; message?: string; phase?: string; retryable?: boolean; server?: string; method?: string; trace_id?: string }; board?: { hypotheses: Hypothesis[]; memory: MemoryEntry[]; strategy_cards?: StrategyCard[] };
  skills?: SkillRef[]; count?: number; memory_id?: string; content?: string; source?: string; last_result?: string; decision?: string; risk?: string; message?: string;
  steer_message?: string; strategy_card_id?: string; strategy_step_id?: string; expected_outcome?: string; retry_reason?: string;
  runtime?: string; tool_call_id?: string; tool_name?: string; arguments?: Record<string, unknown>; artifacts?: Array<{ artifact_id: string; content?: string }>;
  tool_kind?: string; mcp_server?: string; mcp_method?: string; mcp_request_id?: string; trace_id?: string; catalog_version?: string;
  duration_ms?: number; timings?: Record<string, number>; truncated?: boolean; artifact_truncated?: boolean; retryable?: boolean; phase?: string;
  mode?: TaskMode; validator_code?: string; missing?: string[]; evidence_artifact_ids?: string[]; turn?: number; terminal?: boolean;
};
export type AgentEventType = "SESSION_STARTED" | "SESSION_STOPPED" | "SESSION_CONTROLLED" | "SOLVER_STARTED" | "SOLVER_STOPPED" | "MESSAGE_START" | "MESSAGE_END" | "TOOL_EXECUTION_START" | "TOOL_EXECUTION_END" | "AGENT_ERROR" | "AGENT_FINISHED" | "FLAG_FOUND" | "HYPOTHESIS_CREATED" | "HYPOTHESIS_UPDATED" | "HYPOTHESIS_STALLED" | "SKILLS_LOADED" | "PLAN_EMPTY" | "MEMORY_UPSERTED" | "ACTION_PROPOSED" | "ACTION_APPROVED" | "ACTION_STARTED" | "ACTION_FINISHED" | "RESULT_REJECTED" | "OBSERVER_REVIEWED" | "OBSERVER_FAILED" | "GATE_REJECTED" | "FLAG_CONFIRMED" | "FINDING_CONFIRMED" | "USER_HINT" | string;
export type RuntimeEvent = { schema_version?: number; id: string; task_id: string; seq: number; type: AgentEventType; solver_id?: string | null; payload: EventPayload; created_at: string };
export type RuntimeSnapshot = {
  schema_version?: number;
  task: RuntimeTask; session: { status: SessionStatus; turn_count: number; max_turns: number; active_solver_id?: string | null; stop_reason?: string | null };
  solvers: RuntimeSolver[]; challenge: ChallengeView; subagents: RuntimeSubagent[]; board: { hypotheses: Hypothesis[]; memory: MemoryEntry[]; strategy_cards?: StrategyCard[] }; actions: RuntimeAction[];
  flags: ConfirmedFlag[]; findings: RuntimeFinding[]; artifacts: RuntimeArtifact[];
  artifact_indexes?: Array<{ artifact_id: string; document_type: string; extraction_status: string; summary: string; segment_count: number; source_refs: string[] }>;
  http_sessions?: Array<{ profile: string; active?: boolean; origin?: string; origin_count: number; request_count: number; rebuild_count: number; reused?: boolean; cross_process_recovery: boolean }>;
  observer?: { directives: Array<Record<string, unknown>> };
  context_metrics?: Array<{ turn: number; audit_message_count: number; working_message_count: number; working_chars: number; summary_hits: number; artifact_retrievals: number }>;
  events: RuntimeEvent[]; latest_seq: number;
};
export type Capability = { name: string; availability: string; risk: string; modes: TaskMode[]; tools?: Array<{ tool_id: string; availability: string; detail?: string }> };
export type MCPTool = { tool_id: string; provider_name?: string; risk: string; modes?: TaskMode[]; methods: Array<{ name: string; description?: string; input_schema?: Record<string, unknown> }> };
export type MCPCatalog = { availability: string; reason?: string; tools: MCPTool[] };
export type MCPHealthRecord = { tool?: string; server?: string; status?: string; detail?: string; configured?: boolean; enabled?: boolean; reachable?: boolean; discovered?: boolean; visible_for_task?: number | null; runnable?: boolean | null; last_call_at?: string | null; last_call_method?: string | null; last_call_duration_ms?: number | null; last_call_error?: { code?: string; message?: string } | null; tools?: number; transport?: "stdio" | "streamable_http"; protocol_version?: string; server_info?: Record<string, unknown>; discovered_at?: string | null; image?: string | null; endpoint?: string | null; workspace_access?: { mode?: "automatic" | "remote" | "host_process"; mounted_on_task_call?: boolean; container_path?: string; read_only?: boolean; artifacts_path?: string; artifacts_writable?: boolean }; error?: { code?: string; message?: string; phase?: string; retryable?: boolean } | null };
export type MCPHealth = { configured: boolean; checked_at?: string; records: MCPHealthRecord[] };
export type MCPImportResult = {
  server_id: string;
  image: string;
  images?: string[];
  requires_selection?: boolean;
  source_type: "docker-image" | "docker-build" | string;
  config_path: string;
  config_action: "created" | "updated" | string;
  build_log?: string;
  catalog?: MCPHealth;
};
export type MCPDeleteResult = { deleted: boolean; server_id: string; image_deleted: false; catalog: MCPHealth };
export type MCPEnabledResult = { server_id: string; enabled: boolean; catalog: MCPHealth };
export type MCPServerConfig = {
  enabled: boolean;
  transport: "stdio" | "streamable_http";
  enabledTools?: string[];
  stdio?: { source: "docker_image" | "local_process"; image?: string; command?: string; args?: string[]; docker?: { memory?: string | null; cpus?: number | null; pidsLimit?: number | null; network?: string; readOnly?: boolean; capDropAll?: boolean; noNewPrivileges?: boolean } } | null;
  http?: { url: string; verifyTls: boolean; headers?: Record<string, string>; secretRefs?: Record<string, string>; proxyUrl?: string | null; allowSameOriginRedirects?: boolean } | null;
};
export type MCPManagedServer = { id: string; config: MCPServerConfig; status?: MCPHealthRecord | null };
export type MCPServerTools = { server_id: string; status: string; protocol_version?: string; server_info?: Record<string, unknown>; error?: { code?: string; message?: string } | null; tools: Array<{ name: string; description?: string; input_schema?: Record<string, unknown>; enabled: boolean }> };
export type CapabilityCatalog = { capabilities: Capability[]; tools: MCPCatalog };
