import { useState } from "react";
import type { TaskListItem } from "../api/tasks";
import { EmptyState, statusLabel } from "../components/ui/EmptyState";

export function DashboardPage({ tasks, onNew, onOpen, onDelete }: { tasks: TaskListItem[]; onNew: () => void; onOpen: (id: string) => void; onDelete: (id: string) => Promise<void> }) {
  const [confirmDelete, setConfirmDelete] = useState<TaskListItem | null>(null);
  const [deleting, setDeleting] = useState(false);
  const [error, setError] = useState("");
  const counts = ["running", "paused", "blocked", "completed"].map((status) => ({ status, count: tasks.filter((item) => item.status === status).length }));
  const remove = async () => { if (!confirmDelete) return; setDeleting(true); setError(""); try { await onDelete(confirmDelete.task_id); setConfirmDelete(null); } catch (reason) { setError(reason instanceof Error ? reason.message : "删除任务失败"); } finally { setDeleting(false); } };
  return <section className="page-stack dashboard-page"><header className="page-title"><div><span className="eyebrow">TGA / Agent Sessions</span><h1>任务总览</h1><p>统一观察 Session、Solver 工具调用和最新运行事件。</p></div><button onClick={onNew}>新建 Session</button></header><div className="metric-grid">{counts.map((item) => <article className={`metric-card status-${item.status}`} key={item.status}><span>{statusLabel(item.status)}</span><strong>{item.count}</strong><small>{metricHint(item.status)}</small></article>)}</div><section className="surface"><div className="surface-head"><div><h2>Agent Sessions</h2><p>每个任务由持久 Solver 会话直接驱动工具循环。</p></div><span className="schema-chip">Agent runtime</span></div>{error ? <div className="inline-error" role="alert">{error}</div> : null}{tasks.length ? <div className="task-card-grid">{tasks.map((task) => { const turns = task.turn_count ?? 0; const maxTurns = task.max_turns ?? 0; const progress = maxTurns ? Math.min(100, Math.round(turns / maxTurns * 100)) : 0; return <article className="task-card" key={task.task_id}><button className="task-card-open" onClick={() => onOpen(task.task_id)}><div className="task-card-title"><span className={`status-badge ${task.status}`}>{statusLabel(task.status)}</span><span className="schema-chip">{task.mode}</span></div><h3>{task.name || task.task_id}</h3><p title={task.target}>{task.target}</p><div className="task-health"><span><b>{task.active_solvers ?? 0}</b> Solver</span><span><b>{task.artifacts}</b> Artifact</span><span><b>{task.flags}</b> Flag</span><span><b>{task.findings}</b> Finding</span></div><div className="budget-row"><span>Agent 回合 {turns}/{maxTurns || "—"}</span><span>{progress}%</span></div><div className="budget-track"><i style={{ width: `${progress}%` }} /></div><small className="latest-event">{task.latest_event ? `#${task.latest_event.seq ?? "—"} ${task.latest_event.type ?? "event"}` : "尚无运行事件"}</small></button><footer><small>{task.updated_at ? new Date(task.updated_at).toLocaleString() : "等待更新"}</small><button className="task-delete danger-button" disabled={task.status === "running"} title={task.status === "running" ? "运行中的任务需先取消" : "删除历史任务"} onClick={() => setConfirmDelete(task)}>删除</button></footer></article>; })}</div> : <EmptyState label="尚无 Session。创建后会在这里显示运行状态与工具事件。" />}</section>{confirmDelete ? <div className="dialog-backdrop" role="presentation"><section className="confirm-dialog" role="dialog" aria-modal="true" aria-labelledby="delete-task-title"><h2 id="delete-task-title">删除历史任务？</h2><p>将永久删除“{confirmDelete.name || confirmDelete.task_id}”的会话、事件、Artifact 和报告，无法恢复。</p><div><button className="secondary-button" disabled={deleting} onClick={() => setConfirmDelete(null)}>返回</button><button className="danger-button" disabled={deleting} onClick={() => void remove()}>{deleting ? "正在删除…" : "确认删除"}</button></div></section></div> : null}</section>;
}

function metricHint(status: string) { return ({ running: "正在执行受控动作", paused: "等待人工继续", blocked: "需要提示或策略调整", completed: "已通过服务端完成判定" } as Record<string, string>)[status] ?? ""; }
