import { FormEvent, useEffect, useState } from "react";
import { Eye, EyeOff, Plus } from "lucide-react";
import { BACKEND_CAPABILITIES } from "../api/capability-state";
import { getLLMSettings, updateLLMSettings, verifyLLMSettings, type LLMSettings } from "../api/tasks";
import { CapabilityNotice, Chip, DefinitionList, DisabledAction, ProductEmpty, ProductPageHeader, ProductTable, ProductTabs } from "../components/ui/ProductPrimitives";

const TABS = ["Providers", "Model Profiles", "Role Routing", "验证历史"];
type Draft = { base_url: string; model: string; api_key: string; supports_vision: boolean | null; max_output_tokens: number; timeout_seconds: number; temperature: number; reasoning_mode: "auto" | "enabled" | "disabled" };

export function ModelsPage({ onConfiguredChange }: { onConfiguredChange?: (configured: boolean) => void }) {
  const [tab, setTab] = useState("Providers"); const [settings, setSettings] = useState<LLMSettings | null>(null);
  const [draft, setDraft] = useState<Draft>({ base_url: "", model: "", api_key: "", supports_vision: null, max_output_tokens: 1024, timeout_seconds: 60, temperature: 0.2, reasoning_mode: "auto" });
  const [showKey, setShowKey] = useState(false); const [editing, setEditing] = useState(false); const [verifying, setVerifying] = useState(false); const [message, setMessage] = useState("");
  useEffect(() => { void getLLMSettings().then((value) => { setSettings(value); setDraft(fromSettings(value)); }); }, []);
  const save = async (event: FormEvent) => { event.preventDefault(); setMessage(""); try { const next = await updateLLMSettings({ ...draft, api_key: draft.api_key || undefined }); setSettings(next); onConfiguredChange?.(next.configured); setDraft((current) => ({ ...current, api_key: "" })); setEditing(false); setMessage("Provider、模型和凭据设置已保存。API Key 不会回显。"); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "保存失败"); } };
  const verify = async () => { setVerifying(true); setMessage(""); try { const result = await verifyLLMSettings(); setMessage(result.reachable && result.action_tools ? `模型连接与工具协议验证成功：${result.model}` : "模型未返回有效工具调用。"); setSettings(await getLLMSettings()); } catch (reason) { setMessage(reason instanceof Error ? reason.message : "模型验证失败"); setSettings(await getLLMSettings()); } finally { setVerifying(false); } };
  const status = verificationLabel(settings);
  return <section className="product-page models-catalog-page">
    <ProductPageHeader title="Models" description="配置 Provider、模型参数并验证工具调用协议。当前后端仅支持一个 Provider。" action={<DisabledAction reason="尚未提供多 Provider 创建接口"><Plus size={15} />添加 Provider</DisabledAction>} />
    <ProductTabs items={TABS} active={tab} onChange={setTab} />
    {tab === "Providers" ? <>
      <CapabilityNotice state={BACKEND_CAPABILITIES.multiModelProviders.state} reason={BACKEND_CAPABILITIES.multiModelProviders.reason} />
      <ProductTable label="Provider 表格" headers={["Provider 名称", "类型", "状态", "默认模型", "最后验证", "可用模型数", "操作"]}><tr className="selected-row"><td><strong>{providerName(settings?.base_url)}</strong><small>{settings?.base_url || "尚未配置 Endpoint"}</small></td><td>OpenAI-compatible</td><td><Chip tone={settings?.verification_status === "verified" ? "success" : settings?.configured ? "warning" : "neutral"}>{status}</Chip></td><td>{settings?.model || "-"}</td><td>{date(settings?.verification?.verified_at)}</td><td>{settings?.configured ? 1 : 0}</td><td><div className="table-actions"><button onClick={() => setEditing(true)}>配置</button><button disabled title="尚未提供 Provider 删除接口">删除</button></div></td></tr></ProductTable>
      <article className="model-detail-panel"><header><div><span className="detail-kicker">PROVIDER DETAIL</span><h2>{providerName(settings?.base_url)}</h2><p>{settings?.base_url || "配置 Provider Endpoint 后可执行验证"}</p></div><div><Chip tone={settings?.verification_status === "verified" ? "success" : "warning"}>{status}</Chip><button className="secondary-button" disabled={!settings?.configured || verifying} onClick={() => void verify()}>{verifying ? "验证中..." : "验证连接"}</button><button onClick={() => setEditing(true)}>编辑配置</button></div></header>
        <DefinitionList rows={[["类型", "OpenAI-compatible"], ["API Endpoint", settings?.base_url || "-"], ["Model", settings?.model || "-"], ["API Key 状态", settings?.api_key_set ? "已设置（不回显）" : "未设置"], ["验证状态", status], ["最后验证时间", date(settings?.verification?.verified_at)], ["Vision 支持", settings?.supports_vision == null ? "自动探测" : settings.supports_vision ? "支持" : "仅文本"], ["Reasoning Mode", settings?.reasoning_mode || "auto"], ["Temperature", String(settings?.temperature ?? "-")], ["Max Output Tokens", String(settings?.max_output_tokens ?? "-")], ["Timeout", `${settings?.timeout_seconds ?? "-"} 秒`], ["验证结果", settings?.verification?.last_error ? `${settings.verification.last_error.code}: ${settings.verification.last_error.message}` : settings?.verification_status === "verified" ? "工具调用协议已验证" : "尚无验证结果"]]} />
      </article>
    </> : <section className="unsupported-workspace"><CapabilityNotice state="unsupported" reason={`${tab} 后端接口尚未提供。`} /><ProductEmpty title={`暂无 ${tab}`} description="页面结构已保留，未伪造多 Provider、Routing 或历史记录。" /></section>}
    {message ? <p className="settings-message" role="status">{message}</p> : null}
    {editing ? <div className="dialog-backdrop"><form className="model-config-dialog" role="dialog" aria-modal="true" aria-label="Provider 配置" onSubmit={save}><header><div><span className="detail-kicker">PROVIDER CONFIG</span><h2>配置 Provider</h2></div><button type="button" className="icon-button" aria-label="关闭配置" onClick={() => setEditing(false)}>×</button></header><label>Provider Base URL<input required type="url" value={draft.base_url} onChange={(event) => setDraft({ ...draft, base_url: event.target.value })} /></label><label>模型 ID<input required value={draft.model} onChange={(event) => setDraft({ ...draft, model: event.target.value })} /></label><div className="secret-field"><label htmlFor="llm-api-key">API Key</label><div className="secret-input"><input id="llm-api-key" type={showKey ? "text" : "password"} placeholder={settings?.api_key_set ? "已保存，留空表示不修改" : "输入 Provider API Key"} value={draft.api_key} onChange={(event) => setDraft({ ...draft, api_key: event.target.value })} /><button type="button" className="icon-button" aria-label={showKey ? "隐藏 API Key" : "显示 API Key"} onClick={() => setShowKey((value) => !value)}>{showKey ? <EyeOff size={16} /> : <Eye size={16} />}</button></div></div><div className="model-field-grid"><label>视觉输入<select value={draft.supports_vision == null ? "auto" : String(draft.supports_vision)} onChange={(event) => setDraft({ ...draft, supports_vision: event.target.value === "auto" ? null : event.target.value === "true" })}><option value="auto">自动探测</option><option value="true">支持图像输入</option><option value="false">仅文本</option></select></label><label>推理模型模式<select value={draft.reasoning_mode} onChange={(event) => setDraft({ ...draft, reasoning_mode: event.target.value as Draft["reasoning_mode"] })}><option value="auto">自动</option><option value="enabled">开启</option><option value="disabled">关闭</option></select></label><label>最大输出 Token<input aria-label="最大输出 Token" type="number" value={draft.max_output_tokens} onChange={(event) => setDraft({ ...draft, max_output_tokens: Number(event.target.value) })} /></label><label>请求超时（秒）<input aria-label="请求超时" type="number" value={draft.timeout_seconds} onChange={(event) => setDraft({ ...draft, timeout_seconds: Number(event.target.value) })} /></label><label>Temperature<input aria-label="Temperature" type="number" step="0.1" value={draft.temperature} onChange={(event) => setDraft({ ...draft, temperature: Number(event.target.value) })} /></label></div><footer><button type="button" className="secondary-button" onClick={() => setEditing(false)}>取消</button><button>保存设置</button></footer></form></div> : null}
  </section>;
}

function fromSettings(value: LLMSettings): Draft { return { base_url: value.base_url, model: value.model, api_key: "", supports_vision: value.supports_vision ?? null, max_output_tokens: value.max_output_tokens ?? 1024, timeout_seconds: value.timeout_seconds ?? 60, temperature: value.temperature ?? 0.2, reasoning_mode: value.reasoning_mode ?? "auto" }; }
function verificationLabel(settings: LLMSettings | null) { return settings?.verification_status === "verified" ? "验证通过" : settings?.verification_status === "verifying" ? "验证中" : settings?.verification_status === "failed" ? "验证失败" : settings?.verification_status === "stale" ? "需要重新验证" : settings?.configured ? "待验证" : "未配置"; }
function providerName(url?: string) { if (!url) return "OpenAI-compatible Provider"; try { return new URL(url).hostname; } catch { return "OpenAI-compatible Provider"; } }
function date(value?: string | null) { return value ? new Date(value).toLocaleString("zh-CN") : "-"; }
