import { useQuery, useQueryClient } from "@tanstack/react-query";
import { RefreshCw, Save, Search, Shield, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { checkSolverKaliHealth, fetchHostCapabilities, fetchHostCapabilityProfiles, fetchKaliProfiles, fetchSolverDefinitions, fetchSolverKaliHealth, fetchSolverKaliHealthSummary, fetchSolverManifest, updateSolverCapabilities, type KaliHealthStatus, type SolverDefinitionRecord, type SolverKaliHealth } from "../api/catalog-query-adapter";
import { CatalogTable, type Column } from "../components/ui/CatalogTable";
import { ChipList, FieldGrid } from "../components/ui/FieldGrid";
import { EmptyState } from "../components/ui/EmptyState";
import { ErrorState } from "../components/ui/ErrorState";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { RiskBadge } from "../components/ui/RiskBadge";
import { StatusBadge } from "../shared/StatusBadge";
import { MODE_PROFILES } from "../modes";

const ROLES = ["supervisor", "worker", "reviewer", "reporter"];
type KaliCapability = "kali.exec" | "kali.session";
type Draft = { hostProfileId: string; hostAdd: string[]; hostRemove: string[]; profileId: string; capabilities: KaliCapability[] };
export function SolversPage() {
  const [search, setSearch] = useState(""); const [role, setRole] = useState(""); const [mode, setMode] = useState(""); const [selectedId, setSelectedId] = useState<string | null>(null);
  const query = useQuery({ queryKey: ["solvers"], queryFn: () => fetchSolverDefinitions() }); const healthSummary = useQuery({ queryKey: ["solvers", "kali-health"], queryFn: fetchSolverKaliHealthSummary }); const all = useMemo(() => query.data?.items ?? [], [query.data]);
  const healthBySolver = useMemo(() => new Map((healthSummary.data?.items ?? []).map((item) => [item.solver_id, item])), [healthSummary.data]);
  const items = useMemo(() => { const needle = search.trim().toLowerCase(); return all.filter((item) => (!needle || item.id.toLowerCase().includes(needle) || item.specialties.some((value) => value.toLowerCase().includes(needle))) && (!role || item.role === role) && (!mode || item.supported_modes.includes(mode))); }, [all, search, role, mode]);
  const selected = items.find((item) => item.id === selectedId) ?? items[0] ?? null;
  const columns: Array<Column<SolverDefinitionRecord>> = [
    { id: "solver", header: "Solver", render: (row) => <span className="task-name-cell"><strong>{row.id}</strong><small>v{row.version}</small></span> }, { id: "role", header: "角色", render: (row) => row.role },
    { id: "modes", header: "模式", render: (row) => <ChipList values={row.supported_modes.map(modeLabel)} tone="neutral" /> }, { id: "host", header: "Host 能力", render: (row) => row.host_capabilities.length, align: "center" },
    { id: "kali", header: "Kali", render: (row) => healthSummary.isError ? <KaliStatusBadge status="unknown" label="状态获取失败" /> : healthSummary.isLoading ? <KaliStatusBadge status="unknown" label="检查中" /> : <KaliStatusBadge status={healthBySolver.get(row.id)?.status ?? "unknown"} /> },
  ];
  if (query.isLoading) return <div className="ref-page"><LoadingSkeleton label="正在读取 Solver" rows={7} /></div>;
  if (query.isError) return <div className="ref-page"><ErrorState description="无法读取 Solver" actionLabel="重试" onAction={() => void query.refetch()} /></div>;
  return <div className="ref-page"><header className="ref-page-head"><div><h1>Solvers</h1><p>管理 Solver 能力与运行环境</p></div></header><section className="ref-filter-row"><label className="ref-search"><Search size={16} /><input aria-label="搜索 Solver" placeholder="搜索 Solver 或专长" value={search} onChange={(e) => setSearch(e.target.value)} /></label><select aria-label="角色" value={role} onChange={(e) => setRole(e.target.value)}><option value="">全部角色</option>{ROLES.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="模式" value={mode} onChange={(e) => setMode(e.target.value)}><option value="">全部模式</option>{[...new Set(all.flatMap((item) => item.supported_modes))].map((value) => <option key={value}>{modeLabel(value)}</option>)}</select></section>{!items.length ? <EmptyState title="没有匹配的 Solver" /> : <div className="ref-master-detail ref-fill"><CatalogTable fill columns={columns} rows={items} rowKey={(row) => row.id} selectedKey={selected?.id} onSelect={(row) => setSelectedId(row.id)} />{selected ? <SolverDetail record={selected} /> : null}</div>}</div>;
}
function SolverDetail({ record }: { record: SolverDefinitionRecord }) {
  const client = useQueryClient(); const profiles = useQuery({ queryKey: ["kali", "profiles"], queryFn: fetchKaliProfiles }); const hostProfiles = useQuery({ queryKey: ["capabilities", "host-profiles"], queryFn: fetchHostCapabilityProfiles }); const hostCapabilities = useQuery({ queryKey: ["capabilities", "host"], queryFn: fetchHostCapabilities }); const manifest = useQuery({ queryKey: ["solvers", record.id, "manifest", record.supported_modes[0]], queryFn: () => fetchSolverManifest(record.id, record.supported_modes[0]) }); const kaliHealth = useQuery({ queryKey: ["solvers", record.id, "kali-health"], queryFn: () => fetchSolverKaliHealth(record.id) });
  const [editing, setEditing] = useState(false); const [draft, setDraft] = useState<Draft>(draftFrom(record)); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => setDraft(draftFrom(record)), [record]);
  const toggle = (capability: KaliCapability) => setDraft((value) => ({ ...value, capabilities: value.capabilities.includes(capability) ? value.capabilities.filter((item) => item !== capability) : [...value.capabilities, capability] }));
  const save = async () => { setBusy(true); setError(""); try { await updateSolverCapabilities(record.id, { expected_content_sha256: record.content_sha256, host_capability_profile_id: draft.hostProfileId, host_capability_overrides: { add: draft.hostAdd, remove: draft.hostRemove }, kali: draft.capabilities.length ? { profile_id: draft.profileId, capabilities: draft.capabilities } : null }); await Promise.all([client.invalidateQueries({ queryKey: ["solvers"] }), client.invalidateQueries({ queryKey: ["capabilities", "host"] }), client.invalidateQueries({ queryKey: ["capabilities", "kali"] }), client.invalidateQueries({ queryKey: ["kali", "profiles"] }), client.invalidateQueries({ queryKey: ["solvers", record.id, "manifest"] }), client.invalidateQueries({ queryKey: ["solvers", "kali-health"] }), client.invalidateQueries({ queryKey: ["solvers", record.id, "kali-health"] })]); setEditing(false); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败"); } finally { setBusy(false); } };
  const byCategory = Object.entries(record.host_capabilities.reduce<Record<string, typeof record.host_capabilities>>((groups, item) => { (groups[item.category] ??= []).push(item); return groups; }, {}));
  return <section className="ref-detail-panel"><header className="ref-detail-head"><div className="ref-detail-title"><Shield size={18} /><h2>{record.id}</h2><span className="ref-version-chip">v{record.version}</span><StatusBadge value="available" label={record.role} /></div>{editing ? <div className="policy-actions"><button className="ref-secondary-button" onClick={() => { setDraft(draftFrom(record)); setEditing(false); }}><X size={14} />取消</button><button className="ref-primary-button" disabled={busy || !draft.hostProfileId || (draft.capabilities.length > 0 && !draft.profileId)} onClick={() => void save()}><Save size={14} />{busy ? "保存中" : "保存"}</button></div> : <button className="ref-primary-button" onClick={() => setEditing(true)}>编辑能力</button>}</header>{error ? <p className="inline-error" role="alert">{error}</p> : null}<FieldGrid columns={2} fields={[{ label: "角色", value: record.role }, { label: "专长", value: <ChipList values={record.specialties} /> }, { label: "支持模式", value: <ChipList values={record.supported_modes.map(modeLabel)} tone="neutral" /> }, { label: "Host Profile", value: record.host_capability_profile_id }, { label: "默认 Skills", value: <ChipList values={record.required_skill_names} tone="neutral" /> }, { label: "Manifest", value: manifest.isLoading ? "加载中" : manifest.isError ? "不可用" : "已验证" }]} /><section className="ref-detail-body"><h3>Host 能力</h3>{editing ? <HostEditor draft={draft} setDraft={setDraft} role={record.role} profiles={hostProfiles.data?.items ?? []} capabilities={hostCapabilities.data?.items ?? []} /> : byCategory.map(([category, values]) => <div key={category}><h4>{category}</h4><div className="capability-grid">{values.map((item) => <article className="capability-card" key={item.id}><div className="capability-title"><div><h3>{item.id}</h3><p>{item.display_name}</p></div><RiskBadge value={item.risk} /></div><div className="capability-meta"><span>来源</span><small>{item.source}</small></div></article>)}</div></div>)}<h3>Kali Runtime</h3>{editing ? <KaliEditor draft={draft} setDraft={setDraft} toggle={toggle} profiles={profiles.data?.items ?? []} /> : <KaliHealthPanel record={record} health={kaliHealth.data} loading={kaliHealth.isLoading} failed={kaliHealth.isError} onRetry={() => void kaliHealth.refetch()} />}</section></section>;
}
function HostEditor({ draft, setDraft, role, profiles, capabilities }: { draft: Draft; setDraft: (value: Draft) => void; role: SolverDefinitionRecord["role"]; profiles: Awaited<ReturnType<typeof fetchHostCapabilityProfiles>>["items"]; capabilities: Awaited<ReturnType<typeof fetchHostCapabilities>>["items"] }) {
  const base = new Set(profiles.find((item) => item.id === draft.hostProfileId)?.capability_ids ?? []); const selected = new Set([...base, ...draft.hostAdd].filter((id) => !draft.hostRemove.includes(id))); const available = capabilities.filter((item) => item.allowed_roles.includes(role)); const toggle = (id: string) => { const enabled = selected.has(id); if (base.has(id)) setDraft({ ...draft, hostRemove: enabled ? [...draft.hostRemove, id] : draft.hostRemove.filter((item) => item !== id), hostAdd: draft.hostAdd.filter((item) => item !== id) }); else setDraft({ ...draft, hostAdd: enabled ? draft.hostAdd.filter((item) => item !== id) : [...draft.hostAdd, id], hostRemove: draft.hostRemove.filter((item) => item !== id) }); };
  return <div className="skill-editor"><label>Host Profile<select value={draft.hostProfileId} onChange={(event) => setDraft({ ...draft, hostProfileId: event.target.value, hostAdd: [], hostRemove: [] })}>{profiles.map((item) => <option key={item.id} value={item.id}>{item.id}</option>)}</select></label><fieldset><legend>Host 能力覆盖</legend>{available.map((item) => <label key={item.id}><input type="checkbox" checked={selected.has(item.id)} onChange={() => toggle(item.id)} />{item.id}<small>{item.display_name}</small></label>)}</fieldset></div>;
}
function KaliEditor({ draft, setDraft, toggle, profiles }: { draft: Draft; setDraft: (value: Draft) => void; toggle: (value: KaliCapability) => void; profiles: Awaited<ReturnType<typeof fetchKaliProfiles>>["items"] }) {
  const selected = profiles.find((item) => item.id === draft.profileId); return <div className="skill-editor"><label>Kali Profile<select value={draft.profileId} onChange={(e) => { const profile = profiles.find((item) => item.id === e.target.value); setDraft({ ...draft, profileId: e.target.value, capabilities: draft.capabilities.filter((item) => profile?.supported_capabilities.includes(item)) }); }}><option value="">选择 Profile</option>{profiles.map((item) => <option key={item.id} value={item.id}>{item.id} · {item.image}</option>)}</select></label><fieldset><legend>Kali 能力</legend>{(["kali.exec", "kali.session"] as KaliCapability[]).map((capability) => <label key={capability}><input type="checkbox" checked={draft.capabilities.includes(capability)} disabled={Boolean(selected && !selected.supported_capabilities.includes(capability))} onChange={() => toggle(capability)} />{capability}<small>{capability === "kali.exec" ? "一次性命令执行" : "交互式 PTY 会话"}</small></label>)}</fieldset><p className="skill-summary">取消全部能力会移除 Kali Binding，不会提交空能力列表。</p></div>;
}
function KaliHealthPanel({ record, health, loading, failed, onRetry }: { record: SolverDefinitionRecord; health?: SolverKaliHealth; loading: boolean; failed: boolean; onRetry: () => void }) {
  const [checking, setChecking] = useState(false); const [checkMessage, setCheckMessage] = useState("");
  const check = async () => { setChecking(true); setCheckMessage(""); try { await checkSolverKaliHealth(record.id); onRetry(); } catch (reason) { const status = typeof reason === "object" && reason && "status" in reason ? Number(reason.status) : 0; setCheckMessage(status === 501 ? "深度检查暂不可用" : "状态刷新失败"); } finally { setChecking(false); } };
  if (loading) return <div className="kali-health-card"><KaliStatusBadge status="unknown" label="检查中" /><p>正在读取该 Solver 的 Kali 状态。</p></div>;
  if (failed || !health) return <div className="kali-health-card kali-health-error" role="alert"><KaliStatusBadge status="unknown" label="状态获取失败" /><p>无法读取 Kali 健康状态，未将其视为健康。</p><button className="ref-secondary-button" onClick={onRetry}>重试</button></div>;
  if (!health.requires_kali) return <div className="kali-health-card"><header><div><span>Kali Runtime</span><h4>Host only</h4></div><KaliStatusBadge status="host_only" /></header><p>此 Solver 不需要 Kali Runtime。</p></div>;
  return <div className="kali-health-card"><header><div><span>Kali Runtime</span><h4>{health.profile_id}</h4></div><KaliStatusBadge status={health.status} /></header><div className="kali-health-grid"><div><span>Profile</span><strong>{health.profile_id}</strong></div><div><span>Overall</span><KaliStatusBadge status={health.status} /></div><div className="kali-health-wide"><span>Image</span><code>{health.image ?? "未配置"}</code></div><div><span>Image status</span><KaliStatusBadge status={normalizeHealthStatus(health.image_status)} label={healthLabel(health.image_status)} /></div><div><span>Runtime status</span><strong>{runtimeLabel(health.runtime_status)}</strong></div></div>{health.reasons.length ? <div className="kali-health-reasons"><span>Details</span><ul>{health.reasons.map((reason) => <li key={`${reason.code}:${reason.message}`}><strong>{reason.code}</strong>{reason.message}</li>)}</ul></div> : null}{health.missing_executables.length ? <p className="kali-missing-tools">缺少工具：{health.missing_executables.join("、")}</p> : null}<footer><small>{health.checked_at ? `检查时间：${new Date(health.checked_at).toLocaleString()}` : "尚未完成检查"}</small><button className="ref-secondary-button" disabled={checking} onClick={() => void check()}><RefreshCw size={14} />{checking ? "检查中" : "重新检查"}</button></footer>{checkMessage ? <p className="inline-error" role="status">{checkMessage}</p> : null}</div>;
}
function KaliStatusBadge({ status, label }: { status: KaliHealthStatus; label?: string }) { const meta = HEALTH_META[status] ?? HEALTH_META.unknown; return <span className={`status-badge-v2 tone-${meta.tone} status-${status}`} title={meta.description}><i aria-hidden="true" />{label ?? meta.label}</span>; }
const HEALTH_META: Record<KaliHealthStatus, { label: string; tone: "neutral" | "info" | "success" | "warning" | "danger"; description: string }> = {
  host_only: { label: "Host only", tone: "info", description: "此 Solver 不需要 Kali Runtime。" }, unknown: { label: "未知", tone: "warning", description: "尚未获得足够的健康信息。" }, runtime_disabled: { label: "Runtime 已禁用", tone: "neutral", description: "Kali Runtime 当前已关闭。" }, unresolved_digest: { label: "未发布", tone: "warning", description: "镜像尚未写入真实 Registry Digest。" }, image_unreachable: { label: "Registry 不可达", tone: "danger", description: "无法访问镜像 Registry。" }, image_not_found: { label: "镜像不存在", tone: "danger", description: "Registry 中不存在该镜像 digest。" }, image_unverified: { label: "未验证", tone: "warning", description: "镜像尚未完成项目验证流程。" }, toolset_mismatch: { label: "Toolset 不匹配", tone: "danger", description: "镜像 toolset digest 与 Profile 不一致。" }, tools_missing: { label: "工具缺失", tone: "danger", description: "镜像缺少 Profile 要求的命令。" }, runtime_unavailable: { label: "Runtime 不可用", tone: "danger", description: "底层 Runtime Provider 当前不可用。" }, healthy: { label: "健康", tone: "success", description: "镜像和 Runtime 检查均通过。" },
};
function normalizeHealthStatus(status: string): KaliHealthStatus { return status in HEALTH_META ? status as KaliHealthStatus : "unknown"; }
function healthLabel(status: string): string { return HEALTH_META[normalizeHealthStatus(status)].label; }
function runtimeLabel(status: string): string { return ({ disabled: "已禁用", sandboxd_unavailable: "sandboxd 不可用", sandboxd_available: "sandboxd 可用", docker_sandbox_unavailable: "Docker Sandbox 不可用", docker_sandbox_available: "Docker Sandbox 可用", not_applicable: "不适用" } as Record<string, string>)[status] ?? status; }
function modeLabel(mode: string): string { return MODE_PROFILES[mode as keyof typeof MODE_PROFILES]?.label ?? mode; }
function draftFrom(record: SolverDefinitionRecord): Draft { return { hostProfileId: record.host_capability_profile_id, hostAdd: [...record.host_capability_overrides.add], hostRemove: [...record.host_capability_overrides.remove], profileId: record.kali?.profile_id ?? "", capabilities: record.kali?.capabilities ?? [] }; }
