import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Save, Search, Shield, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { fetchKaliProfiles, fetchSolverDefinitions, fetchSolverManifest, updateSolverCapabilities, type SolverDefinitionRecord } from "../api/catalog-query-adapter";
import { CatalogTable, type Column } from "../components/ui/CatalogTable";
import { ChipList, FieldGrid } from "../components/ui/FieldGrid";
import { EmptyState } from "../components/ui/EmptyState";
import { ErrorState } from "../components/ui/ErrorState";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { RiskBadge } from "../components/ui/RiskBadge";
import { StatusBadge } from "../shared/StatusBadge";
import { MODE_PROFILES } from "../modes";

const ROLES = ["supervisor", "worker", "reviewer", "reporter"];
type KaliCapability = "kali.exec" | "kali.session";
type Draft = { profileId: string; capabilities: KaliCapability[] };
export function SolversPage() {
  const [search, setSearch] = useState(""); const [role, setRole] = useState(""); const [mode, setMode] = useState(""); const [selectedId, setSelectedId] = useState<string | null>(null);
  const query = useQuery({ queryKey: ["solvers"], queryFn: () => fetchSolverDefinitions() }); const all = useMemo(() => query.data?.items ?? [], [query.data]);
  const items = useMemo(() => { const needle = search.trim().toLowerCase(); return all.filter((item) => (!needle || item.id.toLowerCase().includes(needle) || item.specialties.some((value) => value.toLowerCase().includes(needle))) && (!role || item.role === role) && (!mode || item.supported_modes.includes(mode))); }, [all, search, role, mode]);
  const selected = items.find((item) => item.id === selectedId) ?? items[0] ?? null;
  const columns: Array<Column<SolverDefinitionRecord>> = [
    { id: "solver", header: "Solver", render: (row) => <span className="task-name-cell"><strong>{row.id}</strong><small>v{row.version}</small></span> }, { id: "role", header: "角色", render: (row) => row.role },
    { id: "modes", header: "模式", render: (row) => <ChipList values={row.supported_modes.map(modeLabel)} tone="neutral" /> }, { id: "host", header: "Host 能力", render: (row) => row.host_capabilities.length, align: "center" },
    { id: "kali", header: "Kali", render: (row) => row.kali ? <ChipList values={row.kali.capabilities} /> : <span className="field-empty">未启用</span> },
  ];
  if (query.isLoading) return <div className="ref-page"><LoadingSkeleton label="正在读取 Solver" rows={7} /></div>;
  if (query.isError) return <div className="ref-page"><ErrorState description="无法读取 Solver" actionLabel="重试" onAction={() => void query.refetch()} /></div>;
  return <div className="ref-page"><header className="ref-page-head"><div><h1>Solvers</h1><p>管理 Solver 能力与运行环境</p></div></header><section className="ref-filter-row"><label className="ref-search"><Search size={16} /><input aria-label="搜索 Solver" placeholder="搜索 Solver 或专长" value={search} onChange={(e) => setSearch(e.target.value)} /></label><select aria-label="角色" value={role} onChange={(e) => setRole(e.target.value)}><option value="">全部角色</option>{ROLES.map((value) => <option key={value}>{value}</option>)}</select><select aria-label="模式" value={mode} onChange={(e) => setMode(e.target.value)}><option value="">全部模式</option>{[...new Set(all.flatMap((item) => item.supported_modes))].map((value) => <option key={value}>{modeLabel(value)}</option>)}</select></section>{!items.length ? <EmptyState title="没有匹配的 Solver" /> : <div className="ref-master-detail ref-fill"><CatalogTable fill columns={columns} rows={items} rowKey={(row) => row.id} selectedKey={selected?.id} onSelect={(row) => setSelectedId(row.id)} />{selected ? <SolverDetail record={selected} /> : null}</div>}</div>;
}
function SolverDetail({ record }: { record: SolverDefinitionRecord }) {
  const client = useQueryClient(); const profiles = useQuery({ queryKey: ["kali", "profiles"], queryFn: fetchKaliProfiles }); const manifest = useQuery({ queryKey: ["solvers", record.id, "manifest", record.supported_modes[0]], queryFn: () => fetchSolverManifest(record.id, record.supported_modes[0]) });
  const [editing, setEditing] = useState(false); const [draft, setDraft] = useState<Draft>({ profileId: record.kali?.profile_id ?? "", capabilities: record.kali?.capabilities ?? [] }); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  useEffect(() => setDraft({ profileId: record.kali?.profile_id ?? "", capabilities: record.kali?.capabilities ?? [] }), [record]);
  const toggle = (capability: KaliCapability) => setDraft((value) => ({ ...value, capabilities: value.capabilities.includes(capability) ? value.capabilities.filter((item) => item !== capability) : [...value.capabilities, capability] }));
  const save = async () => { setBusy(true); setError(""); try { await updateSolverCapabilities(record.id, { host_capability_profile_id: record.host_capability_profile_id, host_capability_overrides: record.host_capability_overrides, kali: draft.capabilities.length ? { profile_id: draft.profileId, capabilities: draft.capabilities } : null }); await Promise.all([client.invalidateQueries({ queryKey: ["solvers"] }), client.invalidateQueries({ queryKey: ["capabilities", "host"] }), client.invalidateQueries({ queryKey: ["capabilities", "kali"] }), client.invalidateQueries({ queryKey: ["kali", "profiles"] }), client.invalidateQueries({ queryKey: ["solvers", record.id, "manifest"] })]); setEditing(false); } catch (reason) { setError(reason instanceof Error ? reason.message : "保存失败"); } finally { setBusy(false); } };
  const byCategory = Object.entries(record.host_capabilities.reduce<Record<string, typeof record.host_capabilities>>((groups, item) => { (groups[item.category] ??= []).push(item); return groups; }, {}));
  return <section className="ref-detail-panel"><header className="ref-detail-head"><div className="ref-detail-title"><Shield size={18} /><h2>{record.id}</h2><span className="ref-version-chip">v{record.version}</span><StatusBadge value="available" label={record.role} /></div>{editing ? <div className="policy-actions"><button className="ref-secondary-button" onClick={() => setEditing(false)}><X size={14} />取消</button><button className="ref-primary-button" disabled={busy || (draft.capabilities.length > 0 && !draft.profileId)} onClick={() => void save()}><Save size={14} />{busy ? "保存中" : "保存"}</button></div> : <button className="ref-primary-button" onClick={() => setEditing(true)}>编辑能力</button>}</header>{error ? <p className="inline-error" role="alert">{error}</p> : null}<FieldGrid columns={2} fields={[{ label: "角色", value: record.role }, { label: "专长", value: <ChipList values={record.specialties} /> }, { label: "支持模式", value: <ChipList values={record.supported_modes.map(modeLabel)} tone="neutral" /> }, { label: "Host Profile", value: record.host_capability_profile_id }, { label: "默认 Skills", value: <ChipList values={record.required_skill_names} tone="neutral" /> }, { label: "Manifest", value: manifest.isLoading ? "加载中" : manifest.isError ? "不可用" : "已验证" }]} /><section className="ref-detail-body"><h3>Host 能力</h3>{byCategory.map(([category, values]) => <div key={category}><h4>{category}</h4><div className="capability-grid">{values.map((item) => <article className="capability-card" key={item.id}><div className="capability-title"><div><h3>{item.id}</h3><p>{item.display_name}</p></div><RiskBadge value={item.risk} /></div><div className="capability-meta"><span>来源</span><small>{item.source}</small></div></article>)}</div></div>)}<h3>Kali 沙箱</h3>{editing ? <KaliEditor draft={draft} setDraft={setDraft} toggle={toggle} profiles={profiles.data?.items ?? []} /> : record.kali ? <KaliSummary record={record} /> : <EmptyState title="Kali 未启用" description="该 Solver 仅使用 Host 能力。" />}</section></section>;
}
function KaliEditor({ draft, setDraft, toggle, profiles }: { draft: Draft; setDraft: (value: Draft) => void; toggle: (value: KaliCapability) => void; profiles: Awaited<ReturnType<typeof fetchKaliProfiles>>["items"] }) {
  const selected = profiles.find((item) => item.id === draft.profileId); return <div className="skill-editor"><label>Kali Profile<select value={draft.profileId} onChange={(e) => { const profile = profiles.find((item) => item.id === e.target.value); setDraft({ profileId: e.target.value, capabilities: draft.capabilities.filter((item) => profile?.supported_capabilities.includes(item)) }); }}><option value="">选择 Profile</option>{profiles.map((item) => <option key={item.id} value={item.id}>{item.id} · {item.image}</option>)}</select></label><fieldset><legend>Kali 能力</legend>{(["kali.exec", "kali.session"] as KaliCapability[]).map((capability) => <label key={capability}><input type="checkbox" checked={draft.capabilities.includes(capability)} disabled={Boolean(selected && !selected.supported_capabilities.includes(capability))} onChange={() => toggle(capability)} />{capability}<small>{capability === "kali.exec" ? "一次性命令执行" : "交互式 PTY 会话"}</small></label>)}</fieldset><p className="skill-summary">取消全部能力会移除 Kali Binding，不会提交空能力列表。</p></div>;
}
function KaliSummary({ record }: { record: SolverDefinitionRecord }) { const kali = record.kali!; return <FieldGrid fields={[{ label: "Profile", value: kali.profile_id }, { label: "镜像", value: <code>{kali.image_name}:{kali.image_tag}</code> }, { label: "镜像摘要", value: kali.image_digest ? <code>{kali.image_digest}</code> : "未固定" }, { label: "能力", value: <ChipList values={kali.capabilities} /> }, { label: "网络", value: kali.network_mode }, { label: "已安装工具", value: <ChipList values={kali.tools.map((item) => item.version ? `${item.name} ${item.version}` : item.name)} tone="neutral" /> }, { label: "资源", value: `${kali.limits.cpu_cores} CPU / ${kali.limits.memory_mb} MB / ${kali.limits.timeout_seconds}s / ${kali.limits.max_processes} processes` }]} />; }
function modeLabel(mode: string): string { return MODE_PROFILES[mode as keyof typeof MODE_PROFILES]?.label ?? mode; }