import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, ChevronRight, Play, RotateCcw } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { fetchTaskDetail, fetchTaskEvidence, fetchTaskHistory, fetchTaskInputs, fetchTaskTeam } from "../api/task-query-adapter";
import type { TaskDetail } from "../api/task-query-adapter";
import { ArtifactPreview } from "../components/ui/ArtifactPreview";
import { EmptyState } from "../components/ui/EmptyState";
import { ErrorState } from "../components/ui/ErrorState";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { PageHeader } from "../components/ui/PageHeader";
import { Timeline } from "../components/ui/Timeline";
import { StatusBadge } from "../shared/StatusBadge";
import { statusLabel } from "../shared/status";
import { MODE_PROFILES } from "../modes";

type DetailTab = "overview" | "directives" | "team" | "inputs" | "results" | "config" | "history";
const TABS: Array<[DetailTab, string]> = [["overview", "概览"], ["directives", "指令与范围"], ["team", "团队"], ["inputs", "输入"], ["results", "结果"], ["config", "配置快照"], ["history", "历史"]];

export function TaskDetailPage({ taskId }: { taskId: string }) {
  const navigate = useNavigate();
  const [tab, setTab] = useState<DetailTab>("overview");
  const detail = useQuery({ queryKey: ["task-detail", taskId], queryFn: () => fetchTaskDetail(taskId) });
  const team = useQuery({ queryKey: ["task-team", taskId], queryFn: () => fetchTaskTeam(taskId), enabled: tab === "team" });
  const inputs = useQuery({ queryKey: ["task-inputs", taskId], queryFn: () => fetchTaskInputs(taskId), enabled: tab === "inputs" });
  const evidence = useQuery({ queryKey: ["task-evidence", taskId], queryFn: () => fetchTaskEvidence(taskId), enabled: tab === "results" });
  const history = useQuery({ queryKey: ["task-history", taskId], queryFn: () => fetchTaskHistory(taskId), enabled: tab === "history" });

  if (detail.isLoading) return <LoadingSkeleton label="正在读取任务详情" rows={6} />;
  if (detail.isError || !detail.data) return <ErrorState title="任务详情加载失败" description={detail.error instanceof Error ? detail.error.message : "找不到任务"} actionLabel="返回任务列表" onAction={() => navigate("/tasks")} />;
  const value = detail.data;
  const setDetailTab = (value: DetailTab) => setTab(value);
  return <section className="page-stack task-detail-page">
    <PageHeader eyebrow="WORKSPACE / TASK DETAIL" title={value.task.name} description={value.task.goal} breadcrumbs={[{ label: "TGA", href: "/" }, { label: "任务", href: "/tasks" }, { label: value.task.name }]} meta={<StatusBadge value={value.lifecycle.status} />} actions={<div className="detail-header-actions"><button className="secondary-button" onClick={() => navigate("/tasks")}><ArrowLeft size={14} />任务列表</button><button className="primary-action" onClick={() => navigate(`/tasks/${encodeURIComponent(taskId)}/runtime`)}><Play size={14} />进入运行</button><button className="secondary-button" onClick={() => navigate(`/tasks/${encodeURIComponent(taskId)}/replay`)}><RotateCcw size={14} />Replay</button></div>} />
    <div className="task-detail-meta"><span>{MODE_PROFILES[value.task.mode as keyof typeof MODE_PROFILES]?.label ?? value.task.mode}</span><span>创建于 {formatDate(value.lifecycle.created_at)}</span><span>更新于 {formatDate(value.lifecycle.updated_at)}</span><span>{value.task_id}</span></div>
    <nav className="detail-tab-list" aria-label="任务详情标签" role="tablist">{TABS.map(([key, label]) => <button key={key} role="tab" aria-selected={tab === key} onClick={() => setDetailTab(key)}>{label}<ChevronRight size={12} aria-hidden="true" /></button>)}</nav>
    <div role="tabpanel" className="task-detail-panel">{tab === "overview" ? <Overview detail={value} onTab={setDetailTab} /> : null}{tab === "directives" ? <Directives detail={value} /> : null}{tab === "team" ? <TeamPanel query={team} /> : null}{tab === "inputs" ? <InputsPanel query={inputs} /> : null}{tab === "results" ? <ResultsPanel query={evidence} /> : null}{tab === "config" ? <ConfigPanel detail={value} /> : null}{tab === "history" ? <HistoryPanel query={history} /> : null}</div>
  </section>;
}

function Overview({ detail, onTab }: { detail: TaskDetail; onTab: (tab: DetailTab) => void }) {
  const lifecycle = detail.lifecycle;
  return <div className="detail-overview-stack"><div className="detail-metric-grid"><Metric label="Intent" value={`${lifecycle.intent_completed}/${lifecycle.intent_total || "-"}`} detail="完成进度" /><Metric label="活动 Solver" value={lifecycle.active_solvers} detail="当前摘要" /><Metric label="确认发现" value={lifecycle.findings} detail="真实证据结果" /><Metric label="Artifact" value={lifecycle.artifacts} detail="已持久化产物" /><Metric label="执行轮次" value={`${lifecycle.turn_count}/${lifecycle.max_turns || "-"}`} detail="Task 预算" /><Metric label="待处理" value={lifecycle.pending_approvals} detail={lifecycle.needs_attention ? "需要人工处理" : "当前无待处理"} /></div><div className="detail-overview-columns"><section className="detail-surface"><header><span>TASK DIRECTIVE</span><h2>任务目标与约束</h2></header><p>{detail.task_spec.objective}</p><button className="text-button" onClick={() => onTab("directives")}>查看完整指令 <ChevronRight size={13} /></button></section><section className="detail-surface"><header><span>EXECUTION POLICY</span><h2>执行边界</h2></header><dl className="compact-detail-list"><Row label="Preset" value={String((detail.config_snapshot.execution_policy as Record<string, unknown>).preset ?? "未投影")} /><Row label="Network" value={String(((detail.config_snapshot.execution_policy as Record<string, unknown>).network as Record<string, unknown> | undefined)?.access ?? "未投影")} /><Row label="High impact" value={String(((detail.config_snapshot.execution_policy as Record<string, unknown>).high_impact as Record<string, unknown> | undefined)?.mode ?? "未投影")} /></dl><button className="text-button" onClick={() => onTab("config")}>查看配置快照 <ChevronRight size={13} /></button></section></div><div className="detail-surface detail-lifecycle"><header><span>LIFECYCLE</span><h2>历史与运行入口</h2></header><dl className="compact-detail-list"><Row label="状态" value={statusLabel(lifecycle.status)} /><Row label="最新事件" value={lifecycle.latest_event ? `#${lifecycle.latest_event.seq} · ${lifecycle.latest_event.type}` : "暂无运行事件"} /><Row label="停止原因" value={lifecycle.stop_reason || "未记录"} /></dl></div></div>;
}

function Directives({ detail }: { detail: TaskDetail }) { return <div className="detail-section-grid"><section className="detail-surface"><header><span>OBJECTIVE</span><h2>TaskDirective / 目标</h2></header><p>{detail.task_spec.objective}</p></section><DirectiveGroup title="正式指令" values={detail.task_spec.instructions} /><DirectiveGroup title="约束" values={detail.task_spec.constraints} /><DirectiveGroup title="成功标准" values={detail.task_spec.success_criteria} /><section className="detail-surface"><header><span>SCOPE</span><h2>Scope 与资源</h2></header><p>{detail.task.task_entry_url || "未设置任务入口 URL"}</p><p>{detail.task_spec.resources.length ? `${detail.task_spec.resources.length} 项授权资源` : "未单独投影资源 Scope，使用任务输入和执行策略。"}</p></section></div>; }
function DirectiveGroup({ title, values }: { title: string; values: Array<Record<string, unknown>> }) { return <section className="detail-surface"><header><span>DIRECTIVES</span><h2>{title}</h2></header>{values.length ? <ul className="detail-bullet-list">{values.map((item, index) => <li key={String(item.id ?? index)}>{String(item.content ?? "")}</li>)}</ul> : <p className="muted-copy">暂无已投影内容</p>}</section>; }

function TeamPanel({ query }: { query: ReturnType<typeof useQuery<any>> }) { if (query.isLoading) return <LoadingSkeleton label="正在读取团队摘要" rows={3} />; if (query.isError) return <ErrorState title="团队摘要加载失败" description="无法读取任务团队" actionLabel="重试" onAction={() => void query.refetch()} />; const value = query.data; if (!value) return null; return <div className="detail-section-grid"><section className="detail-surface"><header><span>TEAM</span><h2>团队摘要</h2></header><dl className="compact-detail-list"><Row label="状态" value={String(value.team.status ?? "未投影")} /><Row label="Supervisor" value={String(value.team.supervisor_solver_id ?? "未实例化")} /><Row label="活动 Solver" value={String(value.team.active_solver_count ?? 0)} /><Row label="并发上限" value={String(value.team.max_active_workers ?? "未投影")} /></dl></section><section className="detail-surface"><header><span>SOLVERS</span><h2>{value.solvers.length} 个 Solver</h2></header><ul className="detail-entity-list">{value.solvers.map((item: Record<string, unknown>) => <li key={String(item.solver_id)}><strong>{String(item.solver_id)}</strong><StatusBadge value={String(item.status ?? "created")} /><small>{String(item.orchestration_role ?? "")}</small></li>)}</ul></section></div>; }
function InputsPanel({ query }: { query: ReturnType<typeof useQuery<any>> }) { if (query.isLoading) return <LoadingSkeleton label="正在读取任务输入" rows={4} />; if (query.isError) return <ErrorState title="任务输入加载失败" description="无法读取任务输入摘要" actionLabel="重试" onAction={() => void query.refetch()} />; const value = query.data; if (!value) return null; return <section className="detail-surface"><header><span>INPUTS</span><h2>输入摘要</h2></header><p>{value.prompt || "没有文字提示词"}</p>{value.files.length ? <div className="detail-input-list">{value.files.map((file: Record<string, unknown>) => <article key={String(file.id)}><strong>{String(file.label ?? file.original_name ?? file.id)}</strong><small>{String(file.mime_type ?? "unknown")} · {String(file.size ?? "-")} bytes</small></article>)}</div> : <EmptyState label="没有上传文件" />}</section>; }
function ResultsPanel({ query }: { query: ReturnType<typeof useQuery<any>> }) { if (query.isLoading) return <LoadingSkeleton label="正在读取任务结果" rows={5} />; if (query.isError) return <ErrorState title="任务结果加载失败" description="无法读取 Evidence 与 Finding" actionLabel="重试" onAction={() => void query.refetch()} />; const value = query.data; if (!value) return null; const findings = value.findings.items ?? []; const artifacts = value.artifacts.items ?? []; return <div className="detail-section-grid"><section className="detail-surface"><header><span>FINDINGS</span><h2>已确认结果摘要</h2></header>{findings.length ? <ul className="detail-entity-list">{findings.map((item: Record<string, unknown>) => <li key={String(item.finding_id)}><div><strong>{String(item.title)}</strong><small>{String(item.target ?? "未指定目标")}</small></div><StatusBadge value={String(item.status ?? "candidate")} /></li>)}</ul> : <EmptyState label="尚无已确认 Finding" />}</section><section className="detail-surface"><header><span>ARTIFACTS</span><h2>证据产物</h2></header>{artifacts.length ? artifacts.slice(0, 6).map((item: Record<string, unknown>) => <ArtifactPreview key={String(item.artifact_id)} title={String(item.artifact_id)} kind={String(item.kind ?? "artifact")} metadata={<span>{String(item.created_at ?? "")}</span>} />) : <EmptyState label="尚无 Artifact" />}</section></div>; }
function ConfigPanel({ detail }: { detail: TaskDetail }) { return <div className="detail-section-grid"><SnapshotBlock title="Mode Config" value={detail.config_snapshot.mode_config} /><SnapshotBlock title="ExecutionPolicy Snapshot" value={detail.config_snapshot.execution_policy} /><SnapshotBlock title="Model Snapshot" value={detail.config_snapshot.model ?? { status: "未配置或未投影" }} /><SnapshotBlock title="MCP Capability Snapshot" value={detail.config_snapshot.mcp_capabilities} /></div>; }
function HistoryPanel({ query }: { query: ReturnType<typeof useQuery<any>> }) { if (query.isLoading) return <LoadingSkeleton label="正在读取任务历史" rows={6} />; if (query.isError) return <ErrorState title="任务历史加载失败" description="无法读取任务时间线" actionLabel="重试" onAction={() => void query.refetch()} />; const events = query.data?.events ?? []; return <section className="detail-surface"><header><span>HISTORY</span><h2>持久化事件历史</h2></header><Timeline items={events.map((event: any) => ({ id: String(event.id ?? event.seq), title: String(event.type), timestamp: formatDate(event.created_at), description: String(event.payload?.summary ?? event.payload?.reason ?? "事件已记录"), tone: event.type.includes("FAILED") ? "danger" : event.type.includes("COMPLETED") ? "success" : "neutral" }))} emptyLabel="暂无历史事件" /></section>; }
function SnapshotBlock({ title, value }: { title: string; value: unknown }) { const rows = flattenSnapshot(value); return <section className="detail-surface"><header><span>SNAPSHOT</span><h2>{title}</h2></header>{rows.length ? <dl className="compact-detail-list">{rows.map(([label, item]) => <Row key={label} label={label} value={item} />)}</dl> : <p className="muted-copy">没有可展示的快照字段</p>}</section>; }
function Metric({ label, value, detail }: { label: string; value: string | number; detail: string }) { return <article className="detail-metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
function Row({ label, value }: { label: string; value: string }) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function formatDate(value?: string | null) { return value ? new Date(value).toLocaleString("zh-CN", { dateStyle: "short", timeStyle: "short" }) : "未记录"; }
function flattenSnapshot(value: unknown, prefix = "", depth = 0): Array<[string, string]> {
  if (depth > 2 || value === null || typeof value !== "object") return prefix ? [[prefix, displayValue(value)]] : [];
  if (Array.isArray(value)) return prefix ? [[prefix, value.map(displayValue).join("、") || "-"]] : [];
  return Object.entries(value as Record<string, unknown>).flatMap(([key, item]) => {
    const label = prefix ? `${prefix}.${key}` : key;
    return item !== null && typeof item === "object" && !Array.isArray(item) ? flattenSnapshot(item, label, depth + 1) : [[label, displayValue(item)] as [string, string]];
  }).slice(0, 24);
}
function displayValue(value: unknown): string { if (Array.isArray(value)) return value.map(displayValue).join("、") || "-"; if (typeof value === "boolean") return value ? "是" : "否"; return value == null || value === "" ? "-" : String(value); }
