import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Plus, RefreshCw, Search, Trash2 } from "lucide-react";
import { useMemo, useState } from "react";
import { fetchHostCapabilities, fetchKaliCapabilities, fetchKaliProfiles, type HostCapabilityRecord, type KaliProfileRecord } from "../api/catalog-query-adapter";
import { runtimeApi } from "../runtime/api-v2";
import type { MCPManagedServer } from "../runtime/event-types";
import { MCPWizard } from "../components/mcp/MCPWizard";
import { ConfirmDialog } from "../components/ui/ConfirmDialog";
import { CatalogTable, type Column } from "../components/ui/CatalogTable";
import { DetailTabs, type DetailTab } from "../components/ui/DetailTabs";
import { ChipList, FieldGrid } from "../components/ui/FieldGrid";
import { EmptyState } from "../components/ui/EmptyState";
import { ErrorState } from "../components/ui/ErrorState";
import { LoadingSkeleton } from "../components/ui/LoadingSkeleton";
import { RiskBadge } from "../components/ui/RiskBadge";
import { StatusBadge } from "../shared/StatusBadge";

const TABS: DetailTab[] = [{ id: "host", label: "Host 能力" }, { id: "kali", label: "Kali 沙箱" }, { id: "mcp", label: "MCP Servers" }];
export function CapabilitiesPage() {
  const [tab, setTab] = useState("host");
  return <div className="ref-page"><header className="ref-page-head"><div><h1>Tools &amp; MCP</h1><p>管理 Host 能力、Kali 沙箱与 MCP 服务</p></div></header><DetailTabs tabs={TABS} active={tab} onSelect={setTab} size="lg" />{tab === "host" ? <HostTab /> : tab === "kali" ? <KaliTab /> : <ServersTab />}</div>;
}
function HostTab() {
  const [search, setSearch] = useState(""); const [category, setCategory] = useState(""); const [role, setRole] = useState(""); const [selectedId, setSelectedId] = useState<string | null>(null);
  const query = useQuery({ queryKey: ["capabilities", "host"], queryFn: fetchHostCapabilities });
  const all = useMemo(() => query.data?.items ?? [], [query.data]);
  const items = useMemo(() => { const needle = search.trim().toLowerCase(); return all.filter((item) => (!needle || `${item.id} ${item.display_name} ${item.description}`.toLowerCase().includes(needle)) && (!category || item.category === category) && (!role || item.allowed_roles.includes(role))); }, [all, search, category, role]);
  const selected = items.find((item) => item.id === selectedId) ?? items[0] ?? null;
  const columns: Array<Column<HostCapabilityRecord>> = [
    { id: "name", header: "能力", render: (row) => <span className="task-name-cell"><strong>{row.id}</strong><small>{row.display_name}</small></span> },
    { id: "category", header: "分类", render: (row) => row.category }, { id: "risk", header: "风险", render: (row) => <RiskBadge value={row.risk} /> },
    { id: "roles", header: "适用角色", render: (row) => <ChipList values={row.allowed_roles} tone="neutral" /> }, { id: "handler", header: "Handler", render: (row) => <StatusBadge value={row.handler_status} label="已实现" /> },
    { id: "solvers", header: "Solver", render: (row) => row.assigned_solver_count, align: "center" },
  ];
  if (query.isLoading) return <LoadingSkeleton label="正在读取 Host 能力" rows={7} />;
  if (query.isError) return <ErrorState description="无法读取 Host 能力" actionLabel="重试" onAction={() => void query.refetch()} />;
  return <><section className="ref-filter-row"><label className="ref-search"><Search size={16} /><input aria-label="搜索 Host 能力" placeholder="搜索能力名称或描述" value={search} onChange={(e) => setSearch(e.target.value)} /></label><select aria-label="能力分类" value={category} onChange={(e) => setCategory(e.target.value)}><option value="">全部分类</option>{[...new Set(all.map((item) => item.category))].map((value) => <option key={value}>{value}</option>)}</select><select aria-label="适用角色" value={role} onChange={(e) => setRole(e.target.value)}><option value="">全部角色</option>{["supervisor", "worker", "reviewer", "reporter"].map((value) => <option key={value}>{value}</option>)}</select></section>{!items.length ? <EmptyState title="没有匹配的 Host 能力" /> : <div className="ref-master-detail tools-layout ref-fill"><CatalogTable fill columns={columns} rows={items} rowKey={(row) => row.id} selectedKey={selected?.id} onSelect={(row) => setSelectedId(row.id)} />{selected ? <section className="ref-detail-panel"><header className="ref-detail-head"><h2>{selected.id}</h2><StatusBadge value={selected.handler_status} label="Handler ready" /></header><p className="skill-summary">{selected.description}</p><FieldGrid fields={[{ label: "显示名称", value: selected.display_name }, { label: "分类", value: selected.category }, { label: "风险", value: <RiskBadge value={selected.risk} /> }, { label: "Handler", value: <code>{selected.handler_key}</code> }, { label: "适用角色", value: <ChipList values={selected.allowed_roles} tone="neutral" /> }, { label: "参数", value: <ChipList values={Object.keys(selected.input_schema.properties ?? {})} /> }, { label: "配置该能力的 Solver", value: <ChipList values={selected.assigned_solver_ids} tone="neutral" /> }]} /></section> : null}</div>}</>;
}
function KaliTab() {
  const capabilities = useQuery({ queryKey: ["capabilities", "kali"], queryFn: fetchKaliCapabilities }); const profiles = useQuery({ queryKey: ["kali", "profiles"], queryFn: fetchKaliProfiles }); const [selectedProfile, setSelectedProfile] = useState<string | null>(null);
  if (capabilities.isLoading || profiles.isLoading) return <LoadingSkeleton label="正在读取 Kali 配置" rows={7} />;
  if (capabilities.isError || profiles.isError) return <ErrorState description="无法读取 Kali 配置" actionLabel="重试" onAction={() => { void capabilities.refetch(); void profiles.refetch(); }} />;
  const profileItems = profiles.data?.items ?? []; const active = profileItems.find((item) => item.id === selectedProfile) ?? profileItems[0] ?? null;
  const columns: Array<Column<KaliProfileRecord>> = [{ id: "profile", header: "Profile", render: (row) => <strong>{row.id}</strong> }, { id: "image", header: "镜像", render: (row) => <code>{row.image}</code> }, { id: "tools", header: "工具", render: (row) => row.tools.length, align: "center" }, { id: "caps", header: "能力", render: (row) => <ChipList values={row.supported_capabilities} /> }, { id: "network", header: "网络", render: (row) => row.network_mode }, { id: "solvers", header: "Solver", render: (row) => row.assigned_solver_count, align: "center" }];
  return <div className="ref-detail-body"><section><h2>Kali 执行能力</h2><div className="capability-grid">{(capabilities.data?.items ?? []).map((item) => <article className="capability-card" key={item.id}><div className="capability-title"><div><h3>{item.id}</h3><p>{item.description}</p></div><RiskBadge value={item.risk} /></div><FieldGrid fields={[{ label: "配置 Solver", value: <ChipList values={item.assigned_solver_ids} /> }, { label: "绑定 Profile", value: <ChipList values={item.profile_ids} tone="neutral" /> }, { label: "参数", value: <ChipList values={Object.keys(item.input_schema.properties ?? {})} tone="neutral" /> }]} /></article>)}</div></section><section><h2>Kali Profiles</h2>{active?.image_role === "universal" ? <p className="skill-summary">全部 Solver Profile 共享通用 Kali 工具镜像；网络、命令白名单和资源限制仍按 Profile 独立执行。</p> : null}<div className="ref-master-detail tools-layout"><CatalogTable columns={columns} rows={profileItems} rowKey={(row) => row.id} selectedKey={active?.id} onSelect={(row) => setSelectedProfile(row.id)} />{active ? <section className="ref-detail-panel"><header className="ref-detail-head"><div><h2>{active.id}</h2><code>{active.image}</code></div><StatusBadge value={active.enabled ? "available" : "unavailable"} /></header><FieldGrid fields={[{ label: "镜像模式", value: active.image_role === "universal" ? `通用镜像（${active.shared_image_profile_count} Profiles）` : "独立镜像" }, { label: "镜像摘要", value: active.image_digest ? <code>{active.image_digest}</code> : "等待发布固定" }, { label: "能力", value: <ChipList values={active.supported_capabilities} /> }, { label: "绑定 Solver", value: <ChipList values={active.assigned_solver_ids} tone="neutral" /> }, { label: "可用工具", value: <ChipList values={active.tools.map((tool) => tool.version ? `${tool.name} ${tool.version}` : tool.name)} tone="neutral" /> }, { label: "网络", value: active.network_mode }, { label: "挂载", value: `Inputs ${active.input_mount} / Scratch ${active.scratch_mount} / Artifacts ${active.shared_artifact_mount}` }, { label: "资源", value: `${active.limits.cpu_cores} CPU / ${active.limits.memory_mb} MB / ${active.limits.timeout_seconds}s` }]} /></section> : null}</div></section></div>;
}
type McpRecord = { server: string; configured: boolean; enabled: boolean; reachable: boolean; discovered: boolean; tools: number; transport: string; image?: string | null; endpoint?: string | null; error?: string | null };
function ServersTab() {
  const client = useQueryClient(); const [selectedId, setSelectedId] = useState<string | null>(null); const [wizard, setWizard] = useState<MCPManagedServer | "new" | null>(null); const [remove, setRemove] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const query = useQuery({ queryKey: ["tools", "health"], queryFn: () => runtimeApi.toolHealth() as Promise<{ records: McpRecord[] }> }); const managed = useQuery({ queryKey: ["mcp", "servers"], queryFn: runtimeApi.mcpServers }); const records = query.data?.records ?? []; const selected = records.find((item) => item.server === selectedId) ?? records[0] ?? null;
  const refresh = () => Promise.all([client.invalidateQueries({ queryKey: ["tools", "health"] }), client.invalidateQueries({ queryKey: ["mcp", "servers"] })]);
  if (query.isLoading) return <LoadingSkeleton label="正在读取 MCP 状态" rows={6} />; if (query.isError) return <ErrorState description="无法读取 MCP 状态" actionLabel="重试" onAction={() => void query.refetch()} />;
  const columns: Array<Column<McpRecord>> = [{ id: "server", header: "服务器", render: (row) => <strong>{row.server}</strong> }, { id: "transport", header: "传输", render: (row) => row.transport }, { id: "enabled", header: "启用", render: (row) => <StatusBadge value={row.enabled ? "available" : "unavailable"} /> }, { id: "reachable", header: "可达", render: (row) => <StatusBadge value={row.reachable ? "healthy" : "unavailable"} /> }, { id: "tools", header: "工具", render: (row) => row.tools, align: "center" }];
  return <><section className="ref-filter-row"><button className="ref-primary-button" onClick={() => setWizard("new")}><Plus size={16} />添加 MCP 服务</button><button className="ref-secondary-button" onClick={() => void refresh()}><RefreshCw size={14} />刷新</button></section>{!records.length ? <EmptyState title="暂无 MCP 服务" /> : <div className="ref-master-detail tools-layout"><CatalogTable columns={columns} rows={records} rowKey={(row) => row.server} selectedKey={selected?.server} onSelect={(row) => setSelectedId(row.server)} />{selected ? <section className="ref-detail-panel"><header className="ref-detail-head"><h2>{selected.server}</h2><div className="policy-actions"><button className="ref-secondary-button" disabled={busy} onClick={async () => { setBusy(true); try { await runtimeApi.updateMCPServer(selected.server, { enabled: !selected.enabled }); await refresh(); } finally { setBusy(false); } }}>{selected.enabled ? "停用" : "启用"}</button>{managed.data?.servers.find((item) => item.id === selected.server) ? <><button className="ref-secondary-button" onClick={() => setWizard(managed.data!.servers.find((item) => item.id === selected.server)!)}>编辑</button><button className="ref-secondary-button" onClick={() => setRemove(selected.server)}><Trash2 size={14} />删除</button></> : null}</div></header><FieldGrid fields={[{ label: "传输", value: selected.transport }, { label: "工具数", value: selected.tools }, { label: "镜像/端点", value: selected.image ?? selected.endpoint ?? "-" }, { label: "错误", value: selected.error ?? "无" }]} /></section> : null}</div>}<ConfirmDialog open={remove !== null} title={`删除 MCP 服务 ${remove ?? ""}`} description="删除后该服务不再进入工具目录。" confirmLabel="删除" danger busy={busy} onCancel={() => setRemove(null)} onConfirm={async () => { if (!remove) return; setBusy(true); try { await runtimeApi.deleteMCPServer(remove); setRemove(null); setSelectedId(null); await refresh(); } finally { setBusy(false); } }} />{wizard !== null ? <MCPWizard initial={wizard === "new" ? undefined : wizard} onClose={() => setWizard(null)} onSaved={() => { setWizard(null); void refresh(); }} /> : null}</>;
}
